# -*- coding: utf-8 -*-
# Copyright (c) 2012, Vehbi Sinan Tunalioglu <vst@vsthost.com>
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
#
# - Redistributions of source code must retain the above copyright
#   notice, this list of conditions and the following disclaimer.
#
# - Redistributions in binary form must reproduce the above copyright
#   notice, this list of conditions and the following disclaimer in
#   the documentation and/or other materials provided with the
#   distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
# FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
# COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
# INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
# BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
# LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
# ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.

__version__ = (0, 0, 0, "dev", 0)

from collections import OrderedDict
from decimal import Decimal
from kountry import Country
from kountry import classproperty
from textwrap import wrap
import csv
import datetime
import json
import re

class Currency(object):
    """
    Provides the canonical representation of a currency object and
    further functionality such as querying.
    """

    _LOOKUP_TABLE = {"code": dict(), "enum": dict(), "name": dict()}
    """
    Provides a lookup table mainly for :attr:`get` class method.
    """

    FIELD_NAMES = ["code", "enum", "name", "common_name", "short_name",
                   "nickname", "symbol", "short_symbol", "decimal_points",
                   "used_in"]
    """
    Provides the field names for the currency model.
    """

    DB = OrderedDict()
    """
    Provides the currency database as an ordered dictionary.
    """

    def __init__(self, code, enum, name, common_name, short_name, nickname,
                 symbol, short_symbol, decimal_points, used_in):
        # Save object attributes:
        self.code = str(code)
        self.enum = ("%03d" % (int(enum))) if (enum != None and enum != "None") else None
        self.name = str(name)
        self.common_name = common_name
        self.short_name = short_name
        self.nickname = nickname
        self.symbol = symbol
        self.short_symbol = short_symbol
        self.decimal_points = int(decimal_points) if decimal_points else None
        self.used_in = used_in

    def __repr__(self):
        return self.name

    def to_dict(self):
        """
        Returns a dictionary version of the currency object.
        """
        return dict(code=self.code,
                    enum=self.enum,
                    name=self.name,
                    common_name=self.common_name,
                    short_name=self.short_name,
                    nickname=self.nickname,
                    symbol=self.symbol,
                    short_symbol=self.short_symbol,
                    decimal_points=self.decimal_points,
                    used_in=self.used_in)

    def to_simple_dict(self):
        """
        Returns a dictionary version of the currency object.
        """
        return dict(code=self.code,
                    enum=self.enum,
                    name=self.name,
                    common_name=self.common_name,
                    short_name=self.short_name,
                    nickname=self.nickname,
                    symbol=self.symbol,
                    short_symbol=self.short_symbol,
                    decimal_points=self.decimal_points,
                    used_in=[item.code_2 for item in self.used_in])

    @classproperty
    def codes(cls):
        """
        Returns all existing currency codes.
        """
        return cls.DB.keys()

    @classproperty
    def dictdb(cls):
        """
        Produces a dictionary version of all of the currencies in the
        database.
        """
        return [currency.to_dict() for key, currency in cls.DB.items()]

    @classmethod
    def get(cls, identifier):
        """
        Queries the :attr:`Currency.DB` for the identifier provided
        and returns the currency object if found, ``None`` otherwise.
        """
        return cls._LOOKUP_TABLE["code"].get(identifier) or \
               cls._LOOKUP_TABLE["enum"].get(identifier) or \
               cls._LOOKUP_TABLE["name"].get(identifier.upper())

    @classmethod
    def put(cls, *args):
        """
        Inserts or overrides given currencies in the DB.

        Note that this method indexes every currency by its
        :attr:`code`, :attr:`enum` and :attr:`name` attributes.
        """
        # Get the tuples by combining existing ones and new ones:
        tuples = cls.DB.items() + [(arg.code, arg) for arg in args]

        # Reset the Database:
        cls.DB = OrderedDict(sorted(tuples, key=lambda x: x[0]))

        # Reset the lookup table (code as the identifier):
        cls._LOOKUP_TABLE["code"] = dict(tuples)

        # Reset the lookup table (enum as the identifier):
        enumed_items = [(item[1].enum, item[1]) for item in tuples]
        cls._LOOKUP_TABLE["enum"] = dict(enumed_items)

        # Reset the lookup table (name as the identifier):
        named_items = [(item[1].name.upper(), item[1]) for item in tuples]
        cls._LOOKUP_TABLE["name"] = dict(named_items)

    @classmethod
    def export_csv(cls, filepath):
        """
        Exports the currency database as a CSV file.
        """
        with open(filepath,"wb") as output:
            writer = csv.DictWriter(output,
                                    fieldnames=cls.FIELD_NAMES,
                                    quoting=csv.QUOTE_NONNUMERIC)
            writer.writeheader()
            writer.writerows(cls.dictdb)

    @classmethod
    def import_csv(cls, filepath):
        """
        Imports a new currency database from a CSV file as a list of
        dictionaries.
        """
        # Declare imported database:
        imported = list()

        with open(filepath) as input:
            # Construct the reader:
            reader = csv.DictReader(input,
                                    #fieldnames=cls.FIELD_NAMES,
                                    quoting=csv.QUOTE_NONNUMERIC)

            # Iterate over items and re-parse when needed:
            for item in reader:
                # Ensure that the decimal points is integer:
                item["decimal_points"] = int(item["decimal_points"]) \
                                         if item["decimal_points"] else None

                # Parse country codes list:
                item["used_in"] = re.compile("\[\]").sub("", item["used_in"])
                item["used_in"] = [c for c in item["used_in"].split(",")]

                # Append to the imported database:
                imported.append(item)

        # Done, return the imported database:
        return imported

    @classmethod
    def db_to_json(cls, db=None):
        """
        Converts the DB to json string.
        """
        # If no db supplied, use cls.DB:
        db = db or cls.DB

        # Generate the json string:
        return json.dumps([item.to_simple_dict() for item in db.values()])


class NoExchangeRateFound(Exception):
    pass


class ExchangeRate(object):
    """
    Defines an exchange rate model.

    TODO: Cache may explode at some point. Take care of it!...
    """

    _PLUGINS = ["kurrency:ExchangeRate#plugin_cache"]
    """
    Defines a list of plugins to use when querying for exchange rates.
    """

    _CACHE = dict()
    """
    Defines a registry for cached rates.
    """

    def __init__(self, cur1, cur2, rate, date=None, time=None, tag=None,
                 source=None, add_to_cache=True):
        # Save the slots:
        self.cur1 = cur1
        self.cur2 = cur2
        self.rate = Decimal(rate)
        self.date = date or datetime.datetime.now().date()
        self.time = time
        self.tag = tag
        self.source = source

        # To cache or not to cache:
        if add_to_cache:
            self._set_to_cache(self)

    @staticmethod
    def _get_cache_key(cur1, cur2, date, time, tag, source):
        """
        Returns an object which is used as the cache key.
        """
        return (cur1, cur2, date, time, tag, source)

    @classmethod
    def _get_from_cache(cls, cur1, cur2, date, time, tag, source):
        """
        Returns the cached value if any, raises exception otherwise.
        """
        key = cls._get_cache_key(cur1, cur2, date, time, tag, source)
        if key in cls._CACHE:
            return cls._CACHE[key]
        raise NoExchangeRateFound("No exchange rate found")

    @classmethod
    def _set_to_cache(cls, exchange_rate):
        """
        Sets the cached value of the exchange rate.
        """
        key = cls._get_cache_key(exchange_rate.cur1,
                                 exchange_rate.cur2,
                                 exchange_rate.date,
                                 exchange_rate.time,
                                 exchange_rate.tag,
                                 exchange_rate.source)
        cls._CACHE[key] = exchange_rate

    @classmethod
    def plugin_cache(cls, cur1, cur2, date=None, time=None, tag=None,
                     source=None):
        """
        Retrieves the exchange rate for the currencies and date/time
        specified.
        """
        return cls._get_from_cache(cur1,
                                   cur2,
                                   date or datetime.datetime.now().date(),
                                   time,
                                   tag,
                                   source)

    @classmethod
    def get(cls, cur1, cur2, date=None, time=None, tag=None, source=None):
        """
        Retrieves the exchange rate for the currencies and date/time
        specified.

        TODO: Avoid repetitive imports of plugins:
        """
        cur1 = Currency.get(cur1) if isinstance(cur1, str) else cur1
        cur2 = Currency.get(cur2) if isinstance(cur2, str) else cur2

        # Create the argument array:
        kwargs = {"cur1": cur1,
                  "cur2": cur2,
                  "date": date or datetime.datetime.now().date(),
                  "time": time,
                  "tag": tag,
                  "source": source}

        # Retrieve the callable array:
        for plugin_path in cls._PLUGINS:
            plugin = cls._get_callable(plugin_path)
            try:
                return plugin(**kwargs)
            except NoExchangeRateFound:
                continue
        raise NoExchangeRateFound("No exchange rate found")

    @staticmethod
    def _get_callable(path):
        module, ccallable = path.split(":")
        try:
            cls, method = ccallable.split("#")
            return getattr(getattr(__import__(module), cls), method)
        except ValueError:
            hep = __import__(module, fromlist=[ccallable])
            return getattr(hep, ccallable)

    @classmethod
    def add_plugin(cls, plugin):
        if not plugin in cls._PLUGINS:
            cls._PLUGINS.append(plugin)
            return True
        return False


#######################
# DATABASE POPULATION #
#######################

RawData = [
    {"code": "AED",
     "name": "United Arab Emirates dirham",
     "short_name": "United Arab Emirates dirham",
     "short_symbol": "",
     "symbol": "",
     "enum": "784",
     "used_in": [u"AE"],
     "decimals": "2",
     "common_name": "United Arab Emirates dirham",
     "nickname": ""},
    {"code": "AFN",
     "name": "Afghan afghani",
     "short_name": "Afghan afghani",
     "short_symbol": "",
     "symbol": "",
     "enum": "971",
     "used_in": ["AF"],
     "decimals": "2",
     "common_name": "Afghan afghani",
     "nickname": ""},
    {"code": "ALL",
     "name": "Albanian lek",
     "short_name": "Albanian lek",
     "short_symbol": "",
     "symbol": "",
     "enum": "008",
     "used_in": ["AL"],
     "decimals": "2",
     "common_name": "Albanian lek",
     "nickname": ""},
    {"code": "AMD",
     "name": "Armenian dram",
     "short_name": "Armenian dram",
     "short_symbol": "",
     "symbol": "",
     "enum": "051",
     "used_in": ["AM"],
     "decimals": "2",
     "common_name": "Armenian dram",
     "nickname": ""},
    {"code": "ANG",
     "name": "Netherlands Antillean guilder",
     "short_name": "Netherlands Antillean guilder",
     "short_symbol": "",
     "symbol": "",
     "enum": "532",
     "used_in": ["CW",
               "SX"],
     "decimals": "2",
     "common_name": "Netherlands Antillean guilder",
     "nickname": ""},
    {"code": "AOA",
     "name": "Angolan kwanza",
     "short_name": "Angolan kwanza",
     "short_symbol": "",
     "symbol": "",
     "enum": "973",
     "used_in": ["AO"],
     "decimals": "2",
     "common_name": "Angolan kwanza",
     "nickname": ""},
    {"code": "ARS",
     "name": "Argentine peso",
     "short_name": "Argentine peso",
     "short_symbol": "",
     "symbol": "",
     "enum": "032",
     "used_in": ["AR"],
     "decimals": "2",
     "common_name": "Argentine peso",
     "nickname": ""},
    {"code": "AUD",
     "name": "Australian dollar",
     "short_name": "Australian dollar",
     "short_symbol": "",
     "symbol": "",
     "enum": "036",
     "used_in": ["AU",
               "CX",
               "CC",
               "HM",
               "KI",
               "NR",
               "NF",
               "TV"],
     "decimals": "2",
     "common_name": "Australian dollar",
     "nickname": ""},
    {"code": "AWG",
     "name": "Aruban florin",
     "short_name": "Aruban florin",
     "short_symbol": "",
     "symbol": "",
     "enum": "533",
     "used_in": ["AW"],
     "decimals": "2",
     "common_name": "Aruban florin",
     "nickname": ""},
    {"code": "AZN",
     "name": "Azerbaijani manat",
     "short_name": "Azerbaijani manat",
     "short_symbol": "",
     "symbol": "",
     "enum": "944",
     "used_in": ["AZ"],
     "decimals": "2",
     "common_name": "Azerbaijani manat",
     "nickname": ""},
    {"code": "BAM",
     "name": "Bosnia and Herzegovina convertible mark",
     "short_name": "Bosnia and Herzegovina convertible mark",
     "short_symbol": "",
     "symbol": "",
     "enum": "977",
     "used_in": ["BA"],
     "decimals": "2",
     "common_name": "Bosnia and Herzegovina convertible mark",
     "nickname": ""},
    {"code": "BBD",
     "name": "Barbados dollar",
     "short_name": "Barbados dollar",
     "short_symbol": "",
     "symbol": "",
     "enum": "052",
     "used_in": ["BB"],
     "decimals": "2",
     "common_name": "Barbados dollar",
     "nickname": ""},
    {"code": "BDT",
     "name": "Bangladeshi taka",
     "short_name": "Bangladeshi taka",
     "short_symbol": "",
     "symbol": "",
     "enum": "050",
     "used_in": ["BD"],
     "decimals": "2",
     "common_name": "Bangladeshi taka",
     "nickname": ""},
    {"code": "BGN",
     "name": "Bulgarian lev",
     "short_name": "Bulgarian lev",
     "short_symbol": "",
     "symbol": "",
     "enum": "975",
     "used_in": ["BG"],
     "decimals": "2",
     "common_name": "Bulgarian lev",
     "nickname": ""},
    {"code": "BHD",
     "name": "Bahraini dinar",
     "short_name": "Bahraini dinar",
     "short_symbol": "",
     "symbol": "",
     "enum": "048",
     "used_in": ["BH"],
     "decimals": "3",
     "common_name": "Bahraini dinar",
     "nickname": ""},
    {"code": "BIF",
     "name": "Burundian franc",
     "short_name": "Burundian franc",
     "short_symbol": "",
     "symbol": "",
     "enum": "108",
     "used_in": ["BI"],
     "decimals": "0",
     "common_name": "Burundian franc",
     "nickname": ""},
    {"code": "BMD",
     "name": "Bermudian dollar (customarily known as Bermuda dollar)",
     "short_name": "Bermudian dollar (customarily known as Bermuda dollar)",
     "short_symbol": "",
     "symbol": "",
     "enum": "060",
     "used_in": ["BM"],
     "decimals": "2",
     "common_name": "Bermudian dollar (customarily known as Bermuda dollar)",
     "nickname": ""},
    {"code": "BND",
     "name": "Brunei dollar",
     "short_name": "Brunei dollar",
     "short_symbol": "",
     "symbol": "",
     "enum": "096",
     "used_in": ["BN",
               "SG"],
     "decimals": "2",
     "common_name": "Brunei dollar",
     "nickname": ""},
    {"code": "BOB",
     "name": "Boliviano",
     "short_name": "Boliviano",
     "short_symbol": "",
     "symbol": "",
     "enum": "068",
     "used_in": ["BO"],
     "decimals": "2",
     "common_name": "Boliviano",
     "nickname": ""},
    {"code": "BOV",
     "name": "Bolivian Mvdol",
     "short_name": "Bolivian Mvdol",
     "short_symbol": "",
     "symbol": "",
     "enum": "984",
     "used_in": ["BO"],
     "decimals": "2",
     "common_name": "Bolivian Mvdol",
     "nickname": ""},
    {"code": "BRL",
     "name": "Brazilian real",
     "short_name": "Brazilian real",
     "short_symbol": "",
     "symbol": "",
     "enum": "986",
     "used_in": ["BR"],
     "decimals": "2",
     "common_name": "Brazilian real",
     "nickname": ""},
    {"code": "BSD",
     "name": "Bahamian dollar",
     "short_name": "Bahamian dollar",
     "short_symbol": "",
     "symbol": "",
     "enum": "044",
     "used_in": ["BS"],
     "decimals": "2",
     "common_name": "Bahamian dollar",
     "nickname": ""},
    {"code": "BTN",
     "name": "Bhutanese ngultrum",
     "short_name": "Bhutanese ngultrum",
     "short_symbol": "",
     "symbol": "",
     "enum": "064",
     "used_in": ["BT"],
     "decimals": "2",
     "common_name": "Bhutanese ngultrum",
     "nickname": ""},
    {"code": "BWP",
     "name": "Botswana pula",
     "short_name": "Botswana pula",
     "short_symbol": "",
     "symbol": "",
     "enum": "072",
     "used_in": ["BW"],
     "decimals": "2",
     "common_name": "Botswana pula",
     "nickname": ""},
    {"code": "BYR",
     "name": "Belarusian ruble",
     "short_name": "Belarusian ruble",
     "short_symbol": "",
     "symbol": "",
     "enum": "974",
     "used_in": ["BY"],
     "decimals": "0",
     "common_name": "Belarusian ruble",
     "nickname": ""},
    {"code": "BZD",
     "name": "Belize dollar",
     "short_name": "Belize dollar",
     "short_symbol": "",
     "symbol": "",
     "enum": "084",
     "used_in": ["BZ"],
     "decimals": "2",
     "common_name": "Belize dollar",
     "nickname": ""},
    {"code": "CAD",
     "name": "Canadian dollar",
     "short_name": "Canadian dollar",
     "short_symbol": "",
     "symbol": "",
     "enum": "124",
     "used_in": ["CA"],
     "decimals": "2",
     "common_name": "Canadian dollar",
     "nickname": ""},
    {"code": "CDF",
     "name": "Congolese franc",
     "short_name": "Congolese franc",
     "short_symbol": "",
     "symbol": "",
     "enum": "976",
     "used_in": ["CD"],
     "decimals": "2",
     "common_name": "Congolese franc",
     "nickname": ""},
    {"code": "CHE",
     "name": "WIR Euro (complementary currency)",
     "short_name": "WIR Euro (complementary currency)",
     "short_symbol": "",
     "symbol": "",
     "enum": "947",
     "used_in": ["CH"],
     "decimals": "2",
     "common_name": "WIR Euro (complementary currency)",
     "nickname": ""},
    {"code": "CHF",
     "name": "Swiss franc",
     "short_name": "Swiss franc",
     "short_symbol": "",
     "symbol": "",
     "enum": "756",
     "used_in": ["CH",
               "LI"],
     "decimals": "2",
     "common_name": "Swiss franc",
     "nickname": ""},
    {"code": "CHW",
     "name": "WIR Franc (complementary currency)",
     "short_name": "WIR Franc (complementary currency)",
     "short_symbol": "",
     "symbol": "",
     "enum": "948",
     "used_in": ["CH"],
     "decimals": "2",
     "common_name": "WIR Franc (complementary currency)",
     "nickname": ""},
    {"code": "CLF",
     "name": "Unidad de Fomento",
     "short_name": "Unidad de Fomento",
     "short_symbol": "",
     "symbol": "",
     "enum": "990",
     "used_in": ["CL"],
     "decimals": "0",
     "common_name": "Unidad de Fomento",
     "nickname": ""},
    {"code": "CLP",
     "name": "Chilean peso",
     "short_name": "Chilean peso",
     "short_symbol": "",
     "symbol": "",
     "enum": "152",
     "used_in": ["CL"],
     "decimals": "0",
     "common_name": "Chilean peso",
     "nickname": ""},
    {"code": "CNY",
     "name": "Chinese yuan",
     "short_name": "Chinese yuan",
     "short_symbol": "",
     "symbol": "",
     "enum": "156",
     "used_in": ["CN"],
     "decimals": "2",
     "common_name": "Chinese yuan",
     "nickname": ""},
    {"code": "COP",
     "name": "Colombian peso",
     "short_name": "Colombian peso",
     "short_symbol": "",
     "symbol": "",
     "enum": "170",
     "used_in": ["CO"],
     "decimals": "2",
     "common_name": "Colombian peso",
     "nickname": ""},
    {"code": "COU",
     "name": "Unidad de Valor Real",
     "short_name": "Unidad de Valor Real",
     "short_symbol": "",
     "symbol": "",
     "enum": "970",
     "used_in": ["CO"],
     "decimals": "2",
     "common_name": "Unidad de Valor Real",
     "nickname": ""},
    {"code": "CRC",
     "name": "Costa Rican colon",
     "short_name": "Costa Rican colon",
     "short_symbol": "",
     "symbol": "",
     "enum": "188",
     "used_in": ["CR"],
     "decimals": "2",
     "common_name": "Costa Rican colon",
     "nickname": ""},
    {"code": "CUC",
     "name": "Cuban convertible peso",
     "short_name": "Cuban convertible peso",
     "short_symbol": "",
     "symbol": "",
     "enum": "931",
     "used_in": ["CU"],
     "decimals": "2",
     "common_name": "Cuban convertible peso",
     "nickname": ""},
    {"code": "CUP",
     "name": "Cuban peso",
     "short_name": "Cuban peso",
     "short_symbol": "",
     "symbol": "",
     "enum": "192",
     "used_in": ["CU"],
     "decimals": "2",
     "common_name": "Cuban peso",
     "nickname": ""},
    {"code": "CVE",
     "name": "Cape Verde escudo",
     "short_name": "Cape Verde escudo",
     "short_symbol": "",
     "symbol": "",
     "enum": "132",
     "used_in": ["CV"],
     "decimals": "0",
     "common_name": "Cape Verde escudo",
     "nickname": ""},
    {"code": "CZK",
     "name": "Czech koruna",
     "short_name": "Czech koruna",
     "short_symbol": "",
     "symbol": "",
     "enum": "203",
     "used_in": ["CZ"],
     "decimals": "2",
     "common_name": "Czech koruna",
     "nickname": ""},
    {"code": "DJF",
     "name": "Djiboutian franc",
     "short_name": "Djiboutian franc",
     "short_symbol": "",
     "symbol": "",
     "enum": "262",
     "used_in": ["DJ"],
     "decimals": "0",
     "common_name": "Djiboutian franc",
     "nickname": ""},
    {"code": "DKK",
     "name": "Danish krone",
     "short_name": "Danish krone",
     "short_symbol": "",
     "symbol": "",
     "enum": "208",
     "used_in": ["DK",
               "FO",
               "GL"],
     "decimals": "2",
     "common_name": "Danish krone",
     "nickname": ""},
    {"code": "DOP",
     "name": "Dominican peso",
     "short_name": "Dominican peso",
     "short_symbol": "",
     "symbol": "",
     "enum": "214",
     "used_in": ["DO"],
     "decimals": "2",
     "common_name": "Dominican peso",
     "nickname": ""},
    {"code": "DZD",
     "name": "Algerian dinar",
     "short_name": "Algerian dinar",
     "short_symbol": "",
     "symbol": "",
     "enum": "012",
     "used_in": ["DZ"],
     "decimals": "2",
     "common_name": "Algerian dinar",
     "nickname": ""},
    {"code": "EGP",
     "name": "Egyptian pound",
     "short_name": "Egyptian pound",
     "short_symbol": "",
     "symbol": "",
     "enum": "818",
     "used_in": ["EG"],
     "decimals": "2",
     "common_name": "Egyptian pound",
     "nickname": ""},
    {"code": "ERN",
     "name": "Eritrean nakfa",
     "short_name": "Eritrean nakfa",
     "short_symbol": "",
     "symbol": "",
     "enum": "232",
     "used_in": ["ER"],
     "decimals": "2",
     "common_name": "Eritrean nakfa",
     "nickname": ""},
    {"code": "ETB",
     "name": "Ethiopian birr",
     "short_name": "Ethiopian birr",
     "short_symbol": "",
     "symbol": "",
     "enum": "230",
     "used_in": ["ET"],
     "decimals": "2",
     "common_name": "Ethiopian birr",
     "nickname": ""},
    {"code": "EUR",
     "name": "Euro",
     "short_name": "Euro",
     "short_symbol": "",
     "symbol": "",
     "enum": "978",
     "used_in": ["AD",
               "AT",
               "BE",
               "CY",
               "EE",
               "FI",
               "FR",
               "DE",
               "GR",
               "IE",
               "IT",
               "XK",
               "LU",
               "MT",
               "MC",
               "ME",
               "NL",
               "PT",
               "SM",
               "SK",
               "SI",
               "ES",
               "VA"],
     "decimals": "2",
     "common_name": "Euro",
     "nickname": ""},
    {"code": "FJD",
     "name": "Fiji dollar",
     "short_name": "Fiji dollar",
     "short_symbol": "",
     "symbol": "",
     "enum": "242",
     "used_in": ["FJ"],
     "decimals": "2",
     "common_name": "Fiji dollar",
     "nickname": ""},
    {"code": "FKP",
     "name": "Falkland Islands pound",
     "short_name": "Falkland Islands pound",
     "short_symbol": "",
     "symbol": "",
     "enum": "238",
     "used_in": ["FK"],
     "decimals": "2",
     "common_name": "Falkland Islands pound",
     "nickname": ""},
    {"code": "GBP",
     "name": "Pound sterling",
     "short_name": "Pound sterling",
     "short_symbol": "",
     "symbol": "",
     "enum": "826",
     "used_in": ["GB",
               "IM",
               "GS",
               "IO"],
     "decimals": "2",
     "common_name": "Pound sterling",
     "nickname": ""},
    {"code": "GEL",
     "name": "Georgian lari",
     "short_name": "Georgian lari",
     "short_symbol": "",
     "symbol": "",
     "enum": "981",
     "used_in": ["GE"],
     "decimals": "2",
     "common_name": "Georgian lari",
     "nickname": ""},
    {"code": "GHS",
     "name": "Ghanaian cedi",
     "short_name": "Ghanaian cedi",
     "short_symbol": "",
     "symbol": "",
     "enum": "936",
     "used_in": ["GH"],
     "decimals": "2",
     "common_name": "Ghanaian cedi",
     "nickname": ""},
    {"code": "GIP",
     "name": "Gibraltar pound",
     "short_name": "Gibraltar pound",
     "short_symbol": "",
     "symbol": "",
     "enum": "292",
     "used_in": ["GI"],
     "decimals": "2",
     "common_name": "Gibraltar pound",
     "nickname": ""},
    {"code": "GMD",
     "name": "Gambian dalasi",
     "short_name": "Gambian dalasi",
     "short_symbol": "",
     "symbol": "",
     "enum": "270",
     "used_in": ["GM"],
     "decimals": "2",
     "common_name": "Gambian dalasi",
     "nickname": ""},
    {"code": "GNF",
     "name": "Guinean franc",
     "short_name": "Guinean franc",
     "short_symbol": "",
     "symbol": "",
     "enum": "324",
     "used_in": ["GN"],
     "decimals": "0",
     "common_name": "Guinean franc",
     "nickname": ""},
    {"code": "GTQ",
     "name": "Guatemalan quetzal",
     "short_name": "Guatemalan quetzal",
     "short_symbol": "",
     "symbol": "",
     "enum": "320",
     "used_in": ["GT"],
     "decimals": "2",
     "common_name": "Guatemalan quetzal",
     "nickname": ""},
    {"code": "GYD",
     "name": "Guyanese dollar",
     "short_name": "Guyanese dollar",
     "short_symbol": "",
     "symbol": "",
     "enum": "328",
     "used_in": ["GY"],
     "decimals": "2",
     "common_name": "Guyanese dollar",
     "nickname": ""},
    {"code": "HKD",
     "name": "Hong Kong dollar",
     "short_name": "Hong Kong dollar",
     "short_symbol": "",
     "symbol": "",
     "enum": "344",
     "used_in": ["HK",
               "MO"],
     "decimals": "2",
     "common_name": "Hong Kong dollar",
     "nickname": ""},
    {"code": "HNL",
     "name": "Honduran lempira",
     "short_name": "Honduran lempira",
     "short_symbol": "",
     "symbol": "",
     "enum": "340",
     "used_in": ["HN"],
     "decimals": "2",
     "common_name": "Honduran lempira",
     "nickname": ""},
    {"code": "HRK",
     "name": "Croatian kuna",
     "short_name": "Croatian kuna",
     "short_symbol": "",
     "symbol": "",
     "enum": "191",
     "used_in": ["HR"],
     "decimals": "2",
     "common_name": "Croatian kuna",
     "nickname": ""},
    {"code": "HTG",
     "name": "Haitian gourde",
     "short_name": "Haitian gourde",
     "short_symbol": "",
     "symbol": "",
     "enum": "332",
     "used_in": ["HT"],
     "decimals": "2",
     "common_name": "Haitian gourde",
     "nickname": ""},
    {"code": "HUF",
     "name": "Hungarian forint",
     "short_name": "Hungarian forint",
     "short_symbol": "",
     "symbol": "",
     "enum": "348",
     "used_in": ["HU"],
     "decimals": "2",
     "common_name": "Hungarian forint",
     "nickname": ""},
    {"code": "IDR",
     "name": "Indonesian rupiah",
     "short_name": "Indonesian rupiah",
     "short_symbol": "",
     "symbol": "",
     "enum": "360",
     "used_in": ["ID"],
     "decimals": "2",
     "common_name": "Indonesian rupiah",
     "nickname": ""},
    {"code": "ILS",
     "name": "Israeli new sheqel",
     "short_name": "Israeli new sheqel",
     "short_symbol": "",
     "symbol": "",
     "enum": "376",
     "used_in": ["IL",
               "PS"],
     "decimals": "2",
     "common_name": "Israeli new sheqel",
     "nickname": ""},
    {"code": "INR",
     "name": "Indian rupee",
     "short_name": "Indian rupee",
     "short_symbol": "",
     "symbol": "",
     "enum": "356",
     "used_in": ["IN"],
     "decimals": "2",
     "common_name": "Indian rupee",
     "nickname": ""},
    {"code": "IQD",
     "name": "Iraqi dinar",
     "short_name": "Iraqi dinar",
     "short_symbol": "",
     "symbol": "",
     "enum": "368",
     "used_in": ["IQ"],
     "decimals": "3",
     "common_name": "Iraqi dinar",
     "nickname": ""},
    {"code": "IRR",
     "name": "Iranian rial",
     "short_name": "Iranian rial",
     "short_symbol": "",
     "symbol": "",
     "enum": "364",
     "used_in": ["IR"],
     "decimals": "0",
     "common_name": "Iranian rial",
     "nickname": ""},
    {"code": "ISK",
     "name": "Icelandic króna",
     "short_name": "Icelandic króna",
     "short_symbol": "",
     "symbol": "",
     "enum": "352",
     "used_in": ["IS"],
     "decimals": "0",
     "common_name": "Icelandic króna",
     "nickname": ""},
    {"code": "JMD",
     "name": "Jamaican dollar",
     "short_name": "Jamaican dollar",
     "short_symbol": "",
     "symbol": "",
     "enum": "388",
     "used_in": ["JM"],
     "decimals": "2",
     "common_name": "Jamaican dollar",
     "nickname": ""},
    {"code": "JOD",
     "name": "Jordanian dinar",
     "short_name": "Jordanian dinar",
     "short_symbol": "",
     "symbol": "",
     "enum": "400",
     "used_in": ["JO"],
     "decimals": "3",
     "common_name": "Jordanian dinar",
     "nickname": ""},
    {"code": "JPY",
     "name": "Japanese yen",
     "short_name": "Japanese yen",
     "short_symbol": "",
     "symbol": "",
     "enum": "392",
     "used_in": ["JP"],
     "decimals": "0",
     "common_name": "Japanese yen",
     "nickname": ""},
    {"code": "KES",
     "name": "Kenyan shilling",
     "short_name": "Kenyan shilling",
     "short_symbol": "",
     "symbol": "",
     "enum": "404",
     "used_in": ["KE"],
     "decimals": "2",
     "common_name": "Kenyan shilling",
     "nickname": ""},
    {"code": "KGS",
     "name": "Kyrgyzstani som",
     "short_name": "Kyrgyzstani som",
     "short_symbol": "",
     "symbol": "",
     "enum": "417",
     "used_in": ["KG"],
     "decimals": "2",
     "common_name": "Kyrgyzstani som",
     "nickname": ""},
    {"code": "KHR",
     "name": "Cambodian riel",
     "short_name": "Cambodian riel",
     "short_symbol": "",
     "symbol": "",
     "enum": "116",
     "used_in": ["KH"],
     "decimals": "2",
     "common_name": "Cambodian riel",
     "nickname": ""},
    {"code": "KMF",
     "name": "Comoro franc",
     "short_name": "Comoro franc",
     "short_symbol": "",
     "symbol": "",
     "enum": "174",
     "used_in": ["KM"],
     "decimals": "0",
     "common_name": "Comoro franc",
     "nickname": ""},
    {"code": "KPW",
     "name": "North Korean won",
     "short_name": "North Korean won",
     "short_symbol": "",
     "symbol": "",
     "enum": "408",
     "used_in": ["KP"],
     "decimals": "0",
     "common_name": "North Korean won",
     "nickname": ""},
    {"code": "KRW",
     "name": "South Korean won",
     "short_name": "South Korean won",
     "short_symbol": "",
     "symbol": "",
     "enum": "410",
     "used_in": ["KR"],
     "decimals": "0",
     "common_name": "South Korean won",
     "nickname": ""},
    {"code": "KWD",
     "name": "Kuwaiti dinar",
     "short_name": "Kuwaiti dinar",
     "short_symbol": "",
     "symbol": "",
     "enum": "414",
     "used_in": ["KW"],
     "decimals": "3",
     "common_name": "Kuwaiti dinar",
     "nickname": ""},
    {"code": "KYD",
     "name": "Cayman Islands dollar",
     "short_name": "Cayman Islands dollar",
     "short_symbol": "",
     "symbol": "",
     "enum": "136",
     "used_in": ["KY"],
     "decimals": "2",
     "common_name": "Cayman Islands dollar",
     "nickname": ""},
    {"code": "KZT",
     "name": "Kazakhstani tenge",
     "short_name": "Kazakhstani tenge",
     "short_symbol": "",
     "symbol": "",
     "enum": "398",
     "used_in": ["KZ"],
     "decimals": "2",
     "common_name": "Kazakhstani tenge",
     "nickname": ""},
    {"code": "LAK",
     "name": "Lao kip",
     "short_name": "Lao kip",
     "short_symbol": "",
     "symbol": "",
     "enum": "418",
     "used_in": ["LA"],
     "decimals": "0",
     "common_name": "Lao kip",
     "nickname": ""},
    {"code": "LBP",
     "name": "Lebanese pound",
     "short_name": "Lebanese pound",
     "short_symbol": "",
     "symbol": "",
     "enum": "422",
     "used_in": ["LB"],
     "decimals": "0",
     "common_name": "Lebanese pound",
     "nickname": ""},
    {"code": "LKR",
     "name": "Sri Lankan rupee",
     "short_name": "Sri Lankan rupee",
     "short_symbol": "",
     "symbol": "",
     "enum": "144",
     "used_in": ["LK"],
     "decimals": "2",
     "common_name": "Sri Lankan rupee",
     "nickname": ""},
    {"code": "LRD",
     "name": "Liberian dollar",
     "short_name": "Liberian dollar",
     "short_symbol": "",
     "symbol": "",
     "enum": "430",
     "used_in": ["LR"],
     "decimals": "2",
     "common_name": "Liberian dollar",
     "nickname": ""},
    {"code": "LSL",
     "name": "Lesotho loti",
     "short_name": "Lesotho loti",
     "short_symbol": "",
     "symbol": "",
     "enum": "426",
     "used_in": ["LS"],
     "decimals": "2",
     "common_name": "Lesotho loti",
     "nickname": ""},
    {"code": "LTL",
     "name": "Lithuanian litas",
     "short_name": "Lithuanian litas",
     "short_symbol": "",
     "symbol": "",
     "enum": "440",
     "used_in": ["LT"],
     "decimals": "2",
     "common_name": "Lithuanian litas",
     "nickname": ""},
    {"code": "LVL",
     "name": "Latvian lats",
     "short_name": "Latvian lats",
     "short_symbol": "",
     "symbol": "",
     "enum": "428",
     "used_in": ["LV"],
     "decimals": "2",
     "common_name": "Latvian lats",
     "nickname": ""},
    {"code": "LYD",
     "name": "Libyan dinar",
     "short_name": "Libyan dinar",
     "short_symbol": "",
     "symbol": "",
     "enum": "434",
     "used_in": ["LY"],
     "decimals": "3",
     "common_name": "Libyan dinar",
     "nickname": ""},
    {"code": "MAD",
     "name": "Moroccan dirham",
     "short_name": "Moroccan dirham",
     "short_symbol": "",
     "symbol": "",
     "enum": "504",
     "used_in": ["MA"],
     "decimals": "2",
     "common_name": "Moroccan dirham",
     "nickname": ""},
    {"code": "MDL",
     "name": "Moldovan leu",
     "short_name": "Moldovan leu",
     "short_symbol": "",
     "symbol": "",
     "enum": "498",
     "used_in": ["MD"],
     "decimals": "2",
     "common_name": "Moldovan leu",
     "nickname": ""},
    {"code": "MGA",
     "name": "Malagasy ariary",
     "short_name": "Malagasy ariary",
     "short_symbol": "",
     "symbol": "",
     "enum": "969",
     "used_in": ["MG"],
     "decimals": "",
     "common_name": "Malagasy ariary",
     "nickname": ""},
    {"code": "MKD",
     "name": "Macedonian denar",
     "short_name": "Macedonian denar",
     "short_symbol": "",
     "symbol": "",
     "enum": "807",
     "used_in": ["MK"],
     "decimals": "2",
     "common_name": "Macedonian denar",
     "nickname": ""},
    {"code": "MMK",
     "name": "Myanma kyat",
     "short_name": "Myanma kyat",
     "short_symbol": "",
     "symbol": "",
     "enum": "104",
     "used_in": ["MM"],
     "decimals": "0",
     "common_name": "Myanma kyat",
     "nickname": ""},
    {"code": "MNT",
     "name": "Mongolian tugrik",
     "short_name": "Mongolian tugrik",
     "short_symbol": "",
     "symbol": "",
     "enum": "496",
     "used_in": ["MN"],
     "decimals": "2",
     "common_name": "Mongolian tugrik",
     "nickname": ""},
    {"code": "MOP",
     "name": "Macanese pataca",
     "short_name": "Macanese pataca",
     "short_symbol": "",
     "symbol": "",
     "enum": "446",
     "used_in": ["MO"],
     "decimals": "2",
     "common_name": "Macanese pataca",
     "nickname": ""},
    {"code": "MRO",
     "name": "Mauritanian ouguiya",
     "short_name": "Mauritanian ouguiya",
     "short_symbol": "",
     "symbol": "",
     "enum": "478",
     "used_in": ["MR"],
     "decimals": "",
     "common_name": "Mauritanian ouguiya",
     "nickname": ""},
    {"code": "MUR",
     "name": "Mauritian rupee",
     "short_name": "Mauritian rupee",
     "short_symbol": "",
     "symbol": "",
     "enum": "480",
     "used_in": ["MU"],
     "decimals": "2",
     "common_name": "Mauritian rupee",
     "nickname": ""},
    {"code": "MVR",
     "name": "Maldivian rufiyaa",
     "short_name": "Maldivian rufiyaa",
     "short_symbol": "",
     "symbol": "",
     "enum": "462",
     "used_in": ["MV"],
     "decimals": "2",
     "common_name": "Maldivian rufiyaa",
     "nickname": ""},
    {"code": "MWK",
     "name": "Malawian kwacha",
     "short_name": "Malawian kwacha",
     "short_symbol": "",
     "symbol": "",
     "enum": "454",
     "used_in": ["MW"],
     "decimals": "2",
     "common_name": "Malawian kwacha",
     "nickname": ""},
    {"code": "MXN",
     "name": "Mexican peso",
     "short_name": "Mexican peso",
     "short_symbol": "",
     "symbol": "",
     "enum": "484",
     "used_in": ["MX"],
     "decimals": "2",
     "common_name": "Mexican peso",
     "nickname": ""},
    {"code": "MXV",
     "name": "Mexican Unidad de Inversion (UDI)",
     "short_name": "Mexican Unidad de Inversion (UDI)",
     "short_symbol": "",
     "symbol": "",
     "enum": "979",
     "used_in": ["MX"],
     "decimals": "2",
     "common_name": "Mexican Unidad de Inversion (UDI)",
     "nickname": ""
     },
    {"code": "MYR",
     "name": "Malaysian ringgit",
     "short_name": "Malaysian ringgit",
     "short_symbol": "",
     "symbol": "",
     "enum": "458",
     "used_in": ["MY"],
     "decimals": "2",
     "common_name": "Malaysian ringgit",
     "nickname": ""},
    {"code": "MZN",
     "name": "Mozambican metical",
     "short_name": "Mozambican metical",
     "short_symbol": "",
     "symbol": "",
     "enum": "943",
     "used_in": ["MZ"],
     "decimals": "2",
     "common_name": "Mozambican metical",
     "nickname": ""},
    {"code": "NAD",
     "name": "Namibian dollar",
     "short_name": "Namibian dollar",
     "short_symbol": "",
     "symbol": "",
     "enum": "516",
     "used_in": ["NA"
               ],
     "decimals": "2",
     "common_name": "Namibian dollar",
     "nickname": ""},
    {"code": "NGN",
     "name": "Nigerian naira",
     "short_name": "Nigerian naira",
     "short_symbol": "",
     "symbol": "",
     "enum": "566",
     "used_in": ["NG"
               ],
     "decimals": "2",
     "common_name": "Nigerian naira",
     "nickname": ""},
    {"code": "NIO",
     "name": "Nicaraguan córdoba",
     "short_name": "Nicaraguan córdoba",
     "short_symbol": "",
     "symbol": "",
     "enum": "558",
     "used_in": [
         "NI"],
     "decimals": "2",
     "common_name": "Nicaraguan córdoba",
     "nickname": ""},
    {"code": "NOK",
     "name": "Norwegian krone",
     "short_name": "Norwegian krone",
     "short_symbol": "",
     "symbol": "",
     "enum": "578",
     "used_in": ["NO",
               "SJ",
               "BV"],
     "decimals": "2",
     "common_name": "Norwegian krone",
     "nickname": ""},
    {"code": "NPR",
     "name": "Nepalese rupee",
     "short_name": "Nepalese rupee",
     "short_symbol": "",
     "symbol": "",
     "enum": "524",
     "used_in": ["NP"],
     "decimals": "2",
     "common_name": "Nepalese rupee",
     "nickname": ""},
    {"code": "NZD",
     "name": "New Zealand dollar",
     "short_name": "New Zealand dollar",
     "short_symbol": "",
     "symbol": "",
     "enum": "554",
     "used_in": ["CK",
               "NZ",
               "NU",
               "PN",
               "TK"],
     "decimals": "2",
     "common_name": "New Zealand dollar",
     "nickname": ""},
    {"code": "OMR",
     "name": "Omani rial",
     "short_name": "Omani rial",
     "short_symbol": "",
     "symbol": "",
     "enum": "512",
     "used_in": ["OM"],
     "decimals": "3",
     "common_name": "Omani rial",
     "nickname": ""},
    {"code": "PAB",
     "name": "Panamanian balboa",
     "short_name": "Panamanian balboa",
     "short_symbol": "",
     "symbol": "",
     "enum": "590",
     "used_in": ["PA"],
     "decimals": "2",
     "common_name": "Panamanian balboa",
     "nickname": ""},
    {"code": "PEN",
     "name": "Peruvian nuevo sol",
     "short_name": "Peruvian nuevo sol",
     "short_symbol": "",
     "symbol": "",
     "enum": "604",
     "used_in": ["PE"],
     "decimals": "2",
     "common_name": "Peruvian nuevo sol",
     "nickname": ""},
    {"code": "PGK",
     "name": "Papua New Guinean kina",
     "short_name": "Papua New Guinean kina",
     "short_symbol": "",
     "symbol": "",
     "enum": "598",
     "used_in": ["PG"],
     "decimals": "2",
     "common_name": "Papua New Guinean kina",
     "nickname": ""},
    {"code": "PHP",
     "name": "Philippine peso",
     "short_name": "Philippine peso",
     "short_symbol": "",
     "symbol": "",
     "enum": "608",
     "used_in": ["PH"],
     "decimals": "2",
     "common_name": "Philippine peso",
     "nickname": ""},
    {"code": "PKR",
     "name": "Pakistani rupee",
     "short_name": "Pakistani rupee",
     "short_symbol": "",
     "symbol": "",
     "enum": "586",
     "used_in": ["PK"],
     "decimals": "2",
     "common_name": "Pakistani rupee",
     "nickname": ""},
    {"code": "PLN",
     "name": "Polish złoty",
     "short_name": "Polish złoty",
     "short_symbol": "",
     "symbol": "",
     "enum": "985",
     "used_in": ["PL"],
     "decimals": "2",
     "common_name": "Polish złoty",
     "nickname": ""},
    {"code": "PYG",
     "name": "Paraguayan guaraní",
     "short_name": "Paraguayan guaraní",
     "short_symbol": "",
     "symbol": "",
     "enum": "600",
     "used_in": ["PY"],
     "decimals": "0",
     "common_name": "Paraguayan guaraní",
     "nickname": ""},
    {"code": "QAR",
     "name": "Qatari riyal",
     "short_name": "Qatari riyal",
     "short_symbol": "",
     "symbol": "",
     "enum": "634",
     "used_in": ["QA"],
     "decimals": "2",
     "common_name": "Qatari riyal",
     "nickname": ""},
    {"code": "RON",
     "name": "Romanian new leu",
     "short_name": "Romanian new leu",
     "short_symbol": "",
     "symbol": "",
     "enum": "946",
     "used_in": ["RO"],
     "decimals": "2",
     "common_name": "Romanian new leu",
     "nickname": ""},
    {"code": "RSD",
     "name": "Serbian dinar",
     "short_name": "Serbian dinar",
     "short_symbol": "",
     "symbol": "",
     "enum": "941",
     "used_in": ["RS"],
     "decimals": "2",
     "common_name": "Serbian dinar",
     "nickname": ""},
    {"code": "RUB",
     "name": "Russian rouble",
     "short_name": "Russian rouble",
     "short_symbol": "",
     "symbol": "",
     "enum": "643",
     "used_in": ["RU"],
     "decimals": "2",
     "common_name": "Russian rouble",
     "nickname": ""},
    {"code": "RWF",
     "name": "Rwandan franc",
     "short_name": "Rwandan franc",
     "short_symbol": "",
     "symbol": "",
     "enum": "646",
     "used_in": ["RW"],
     "decimals": "0",
     "common_name": "Rwandan franc",
     "nickname": ""},
    {"code": "SAR",
     "name": "Saudi riyal",
     "short_name": "Saudi riyal",
     "short_symbol": "",
     "symbol": "",
     "enum": "682",
     "used_in": ["SA"],
     "decimals": "2",
     "common_name": "Saudi riyal",
     "nickname": ""},
    {"code": "SBD",
     "name": "Solomon Islands dollar",
     "short_name": "Solomon Islands dollar",
     "short_symbol": "",
     "symbol": "",
     "enum": "090",
     "used_in": ["SB"],
     "decimals": "2",
     "common_name": "Solomon Islands dollar",
     "nickname": ""},
    {"code": "SCR",
     "name": "Seychelles rupee",
     "short_name": "Seychelles rupee",
     "short_symbol": "",
     "symbol": "",
     "enum": "690",
     "used_in": ["SC"],
     "decimals": "2",
     "common_name": "Seychelles rupee",
     "nickname": ""},
    {"code": "SDG",
     "name": "Sudanese pound",
     "short_name": "Sudanese pound",
     "short_symbol": "",
     "symbol": "",
     "enum": "938",
     "used_in": ["SD"],
     "decimals": "2",
     "common_name": "Sudanese pound",
     "nickname": ""},
    {"code": "SEK",
     "name": "Swedish krona/kronor",
     "short_name": "Swedish krona/kronor",
     "short_symbol": "",
     "symbol": "",
     "enum": "752",
     "used_in": ["SE"],
     "decimals": "2",
     "common_name": "Swedish krona/kronor",
     "nickname": ""},
    {"code": "SGD",
     "name": "Singapore dollar",
     "short_name": "Singapore dollar",
     "short_symbol": "",
     "symbol": "",
     "enum": "702",
     "used_in": ["SG",
               "BN"],
     "decimals": "2",
     "common_name": "Singapore dollar",
     "nickname": ""},
    {"code": "SHP",
     "name": "Saint Helena pound",
     "short_name": "Saint Helena pound",
     "short_symbol": "",
     "symbol": "",
     "enum": "654",
     "used_in": ["SH"],
     "decimals": "2",
     "common_name": "Saint Helena pound",
     "nickname": ""},
    {"code": "SLL",
     "name": "Sierra Leonean leone",
     "short_name": "Sierra Leonean leone",
     "short_symbol": "",
     "symbol": "",
     "enum": "694",
     "used_in": ["SL"],
     "decimals": "0",
     "common_name": "Sierra Leonean leone",
     "nickname": ""},
    {"code": "SOS",
     "name": "Somali shilling",
     "short_name": "Somali shilling",
     "short_symbol": "",
     "symbol": "",
     "enum": "706",
     "used_in": ["SO"],
     "decimals": "2",
     "common_name": "Somali shilling",
     "nickname": ""},
    {"code": "SRD",
     "name": "Surinamese dollar",
     "short_name": "Surinamese dollar",
     "short_symbol": "",
     "symbol": "",
     "enum": "968",
     "used_in": ["SR"],
     "decimals": "2",
     "common_name": "Surinamese dollar",
     "nickname": ""},
    {"code": "SSP",
     "name": "South Sudanese pound",
     "short_name": "South Sudanese pound",
     "short_symbol": "",
     "symbol": "",
     "enum": "728",
     "used_in": ["SS"],
     "decimals": "2",
     "common_name": "South Sudanese pound",
     "nickname": ""},
    {"code": "STD",
     "name": "São Tomé and Príncipe dobra",
     "short_name": "São Tomé and Príncipe dobra",
     "short_symbol": "",
     "symbol": "",
     "enum": "678",
     "used_in": ["ST"],
     "decimals": "0",
     "common_name": "São Tomé and Príncipe dobra",
     "nickname": ""},
    {"code": "SYP",
     "name": "Syrian pound",
     "short_name": "Syrian pound",
     "short_symbol": "",
     "symbol": "",
     "enum": "760",
     "used_in": ["SY"],
     "decimals": "2",
     "common_name": "Syrian pound",
     "nickname": ""},
    {"code": "SZL",
     "name": "Swazi lilangeni",
     "short_name": "Swazi lilangeni",
     "short_symbol": "",
     "symbol": "",
     "enum": "748",
     "used_in": ["SZ"],
     "decimals": "2",
     "common_name": "Swazi lilangeni",
     "nickname": ""},
    {"code": "THB",
     "name": "Thai baht",
     "short_name": "Thai baht",
     "short_symbol": "",
     "symbol": "",
     "enum": "764",
     "used_in": ["TH"],
     "decimals": "2",
     "common_name": "Thai baht",
     "nickname": ""},
    {"code": "TJS",
     "name": "Tajikistani somoni",
     "short_name": "Tajikistani somoni",
     "short_symbol": "",
     "symbol": "",
     "enum": "972",
     "used_in": ["TJ"],
     "decimals": "2",
     "common_name": "Tajikistani somoni",
     "nickname": ""},
    {"code": "TMT",
     "name": "Turkmenistani manat",
     "short_name": "Turkmenistani manat",
     "short_symbol": "",
     "symbol": "",
     "enum": "934",
     "used_in": ["TM"],
     "decimals": "2",
     "common_name": "Turkmenistani manat",
     "nickname": ""},
    {"code": "TND",
     "name": "Tunisian dinar",
     "short_name": "Tunisian dinar",
     "short_symbol": "",
     "symbol": "",
     "enum": "788",
     "used_in": ["TN"],
     "decimals": "3",
     "common_name": "Tunisian dinar",
     "nickname": ""},
    {"code": "TOP",
     "name": "Tongan paʻanga",
     "short_name": "Tongan paʻanga",
     "short_symbol": "",
     "symbol": "",
     "enum": "776",
     "used_in": ["TO"],
     "decimals": "2",
     "common_name": "Tongan paʻanga",
     "nickname": ""},
    {"code": "TRY",
     "name": "Turkish lira",
     "short_name": "Turkish lira",
     "short_symbol": "",
     "symbol": "",
     "enum": "949",
     "used_in": ["TR"],
     "decimals": "2",
     "common_name": "Turkish lira",
     "nickname": ""},
    {"code": "TTD",
     "name": "Trinidad and Tobago dollar",
     "short_name": "Trinidad and Tobago dollar",
     "short_symbol": "",
     "symbol": "",
     "enum": "780",
     "used_in": ["TT"],
     "decimals": "2",
     "common_name": "Trinidad and Tobago dollar",
     "nickname": ""},
    {"code": "TWD",
     "name": "New Taiwan dollar",
     "short_name": "New Taiwan dollar",
     "short_symbol": "",
     "symbol": "",
     "enum": "901",
     "used_in": ["TW"],
     "decimals": "2",
     "common_name": "New Taiwan dollar",
     "nickname": ""},
    {"code": "TZS",
     "name": "Tanzanian shilling",
     "short_name": "Tanzanian shilling",
     "short_symbol": "",
     "symbol": "",
     "enum": "834",
     "used_in": ["TZ"],
     "decimals": "2",
     "common_name": "Tanzanian shilling",
     "nickname": ""},
    {"code": "UAH",
     "name": "Ukrainian hryvnia",
     "short_name": "Ukrainian hryvnia",
     "short_symbol": "",
     "symbol": "",
     "enum": "980",
     "used_in": ["UA"],
     "decimals": "2",
     "common_name": "Ukrainian hryvnia",
     "nickname": ""},
    {"code": "UGX",
     "name": "Ugandan shilling",
     "short_name": "Ugandan shilling",
     "short_symbol": "",
     "symbol": "",
     "enum": "800",
     "used_in": ["UG"],
     "decimals": "2",
     "common_name": "Ugandan shilling",
     "nickname": ""},
    {"code": "USD",
     "name": "United States dollar",
     "short_name": "United States dollar",
     "short_symbol": "",
     "symbol": "",
     "enum": "840",
     "used_in": ["AS",
               "BB",
               "BM",
               "IO",
               "VG",
               "EC",
               "SV",
               "GU",
               "HT",
               "MH",
               "FM",
               "MP",
               "PW",
               "PA",
               "PR",
               "TC",
               "US",
               "VI",
               "ZW"],
     "decimals": "2",
     "common_name": "United States dollar",
     "nickname": ""},
    {"code": "USN",
     "name": "United States dollar (next day)",
     "short_name": "United States dollar (next day)",
     "short_symbol": "",
     "symbol": "",
     "enum": "997",
     "used_in": ["US"],
     "decimals": "2",
     "common_name": "United States dollar (next day)",
     "nickname": ""},
    {"code": "USS",
     "name": "United States dollar (same day)",
     "short_name": "United States dollar (same day)",
     "short_symbol": "",
     "symbol": "",
     "enum": "998",
     "used_in": ["US"],
     "decimals": "2",
     "common_name": "United States dollar (same day)",
     "nickname": ""},
    {"code": "UYI",
     "name": "Uruguay Peso en Unidades Indexadas (URUIURUI)",
     "short_name": "Uruguay Peso en Unidades Indexadas (URUIURUI)",
     "short_symbol": "",
     "symbol": "",
     "enum": "940",
     "used_in": ["UY"],
     "decimals": "0",
     "common_name": "Uruguay Peso en Unidades Indexadas (URUIURUI)",
     "nickname": ""},
    {"code": "UYU",
     "name": "Uruguayan peso",
     "short_name": "Uruguayan peso",
     "short_symbol": "",
     "symbol": "",
     "enum": "858",
     "used_in": ["UY"],
     "decimals": "2",
     "common_name": "Uruguayan peso",
     "nickname": ""},
    {"code": "UZS",
     "name": "Uzbekistan som",
     "short_name": "Uzbekistan som",
     "short_symbol": "",
     "symbol": "",
     "enum": "860",
     "used_in": ["UZ"],
     "decimals": "2",
     "common_name": "Uzbekistan som",
     "nickname": ""},
    {"code": "VEF",
     "name": "Venezuelan bolívar fuerte",
     "short_name": "Venezuelan bolívar fuerte",
     "short_symbol": "",
     "symbol": "",
     "enum": "937",
     "used_in": ["VE"],
     "decimals": "2",
     "common_name": "Venezuelan bolívar fuerte",
     "nickname": ""},
    {"code": "VND",
     "name": "Vietname dong",
     "short_name": "Vietname dong",
     "short_symbol": "",
     "symbol": "",
     "enum": "704",
     "used_in": ["VN"],
     "decimals": "0",
     "common_name": "Vietname dong",
     "nickname": ""},
    {"code": "VUV",
     "name": "Vanuatu vatu",
     "short_name": "Vanuatu vatu",
     "short_symbol": "",
     "symbol": "",
     "enum": "548",
     "used_in": ["VU"],
     "decimals": "0",
     "common_name": "Vanuatu vatu",
     "nickname": ""},
    {"code": "WST",
     "name": "Samoan tala",
     "short_name": "Samoan tala",
     "short_symbol": "",
     "symbol": "",
     "enum": "882",
     "used_in": ["WS"],
     "decimals": "2",
     "common_name": "Samoan tala",
     "nickname": ""},
    {"code": "XAF",
     "name": "CFA franc BEAC",
     "short_name": "CFA franc BEAC",
     "short_symbol": "",
     "symbol": "",
     "enum": "950",
     "used_in": ["CM",
               "CF",
               "CG",
               "TD",
               "GQ",
               "GA"],
     "decimals": "0",
     "common_name": "CFA franc BEAC",
     "nickname": ""},
    {"code": "XAG",
     "name": "Silver (one troy ounce)",
     "short_name": "Silver (one troy ounce)",
     "short_symbol": "",
     "symbol": "",
     "enum": "961",
     "used_in": [],
     "decimals": "0",
     "common_name": "Silver (one troy ounce)",
     "nickname": ""},
    {"code": "XAU",
     "name": "Gold (one troy ounce)",
     "short_name": "Gold (one troy ounce)",
     "short_symbol": "",
     "symbol": "",
     "enum": "959",
     "used_in": [],
     "decimals": "0",
     "common_name": "Gold (one troy ounce)",
     "nickname": ""},
    {"code": "XBA",
     "name": "European Composite Unit (EURCO)",
     "short_name": "European Composite Unit (EURCO)",
     "short_symbol": "",
     "symbol": "",
     "enum": "955",
     "used_in": [],
     "decimals": "0",
     "common_name": "European Composite Unit (EURCO)",
     "nickname": ""},
    {"code": "XBB",
     "name": "European Monetary Unit (E.M.U.-6)",
     "short_name": "European Monetary Unit (E.M.U.-6)",
     "short_symbol": "",
     "symbol": "",
     "enum": "956",
     "used_in": [],
     "decimals": "0",
     "common_name": "European Monetary Unit (E.M.U.-6)",
     "nickname": ""},
    {"code": "XBC",
     "name": "European Unit of Account 9 (E.U.A.-9)",
     "short_name": "European Unit of Account 9 (E.U.A.-9)",
     "short_symbol": "",
     "symbol": "",
     "enum": "957",
     "used_in": [],
     "decimals": "0",
     "common_name": "European Unit of Account 9 (E.U.A.-9)",
     "nickname": ""},
    {"code": "XBD",
     "name": "European Unit of Account 17 (E.U.A.-17)",
     "short_name": "European Unit of Account 17 (E.U.A.-17)",
     "short_symbol": "",
     "symbol": "",
     "enum": "958",
     "used_in": [],
     "decimals": "0",
     "common_name": "European Unit of Account 17 (E.U.A.-17)",
     "nickname": ""},
    {"code": "XCD",
     "name": "East Caribbean dollar",
     "short_name": "East Caribbean dollar",
     "short_symbol": "",
     "symbol": "",
     "enum": "951",
     "used_in": ["AI",
               "AG",
               "DM",
               "GD",
               "MS",
               "KN",
               "LC",
               "VC"],
     "decimals": "2",
     "common_name": "East Caribbean dollar",
     "nickname": ""},
    {"code": "XDR",
     "name": "Special drawing rights",
     "short_name": "Special drawing rights",
     "short_symbol": "",
     "symbol": "",
     "enum": "960",
     "used_in": [],
     "decimals": "0",
     "common_name": "Special drawing rights",
     "nickname": ""},
    {"code": "XFU",
     "name": "UIC franc (special settlement currency)",
     "short_name": "UIC franc (special settlement currency)",
     "short_symbol": "",
     "symbol": "",
     "enum": None,
     "used_in": [],
     "decimals": "0",
     "common_name": "UIC franc (special settlement currency)",
     "nickname": ""},
    {"code": "XOF",
     "name": "CFA Franc BCEAO",
     "short_name": "CFA Franc BCEAO",
     "short_symbol": "",
     "symbol": "",
     "enum": "952",
     "used_in": ["BJ",
               "BF",
               "GW",
               "ML",
               "NE",
               "SN",
               "TG"],
     "decimals": "0",
     "common_name": "CFA Franc BCEAO",
     "nickname": ""},
    {"code": "XPD",
     "name": "Palladium (one troy ounce)",
     "short_name": "Palladium (one troy ounce)",
     "short_symbol": "",
     "symbol": "",
     "enum": "964",
     "used_in": [],
     "decimals": "0",
     "common_name": "Palladium (one troy ounce)",
     "nickname": ""},
    {"code": "XPF",
     "name": "CFP franc",
     "short_name": "CFP franc",
     "short_symbol": "",
     "symbol": "",
     "enum": "953",
     "used_in": ["PF",
               "NC",
               "WF"],
     "decimals": "0",
     "common_name": "CFP franc",
     "nickname": ""},
    {"code": "XPT",
     "name": "Platinum (one troy ounce)",
     "short_name": "Platinum (one troy ounce)",
     "short_symbol": "",
     "symbol": "",
     "enum": "962",
     "used_in": [],
     "decimals": "0",
     "common_name": "Platinum (one troy ounce)",
     "nickname": ""},
    {"code": "XTS",
     "name": "Code reserved for testing purposes",
     "short_name": "Code reserved for testing purposes",
     "short_symbol": "",
     "symbol": "",
     "enum": "963",
     "used_in": [],
     "decimals": "0",
     "common_name": "Code reserved for testing purposes",
     "nickname": ""},
    {"code": "XXX",
     "name": "No currency",
     "short_name": "No currency",
     "short_symbol": "",
     "symbol": "",
     "enum": "999",
     "used_in": [],
     "decimals": "0",
     "common_name": "No currency",
     "nickname": ""},
    {"code": "YER",
     "name": "Yemeni rial",
     "short_name": "Yemeni rial",
     "short_symbol": "",
     "symbol": "",
     "enum": "886",
     "used_in": ["YE"],
     "decimals": "2",
     "common_name": "Yemeni rial",
     "nickname": ""},
    {"code": "ZAR",
     "name": "South African rand",
     "short_name": "South African rand",
     "short_symbol": "",
     "symbol": "",
     "enum": "710",
     "used_in": ["ZA"],
     "decimals": "2",
     "common_name": "South African rand",
     "nickname": ""},
    {"code": "ZMK",
     "name": "Zambian kwacha",
     "short_name": "Zambian kwacha",
     "short_symbol": "",
     "symbol": "",
     "enum": "894",
     "used_in": ["ZM"],
     "decimals": "2",
     "common_name": "Zambian kwacha",
     "nickname": ""},
    {"code": "ZWL",
     "name": "Zimbabwe dollar",
     "short_name": "Zimbabwe dollar",
     "short_symbol": "",
     "symbol": "",
     "enum": "932",
     "used_in": ["ZW"],
     "decimals": "2",
     "common_name": "Zimbabwe dollar",
     "nickname": ""}]

# Iterate over the raw currency data and populate currencies database:
Currency.put(*[Currency(currency["code"],
                        currency["enum"],
                        currency["name"],
                        currency["common_name"],
                        currency["short_name"],
                        currency["nickname"],
                        currency["symbol"],
                        currency["short_symbol"],
                        currency["decimals"],
                        [Country.get(code) for code in currency["used_in"]])
               for currency in RawData])
