# -*- coding: utf-8 -*-
# Copyright (c) 2012, Vehbi Sinan Tunalioglu <vst@vsthost.com>
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
#
# - Redistributions of source code must retain the above copyright
#   notice, this list of conditions and the following disclaimer.
#
# - Redistributions in binary form must reproduce the above copyright
#   notice, this list of conditions and the following disclaimer in
#   the documentation and/or other materials provided with the
#   distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
# FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
# COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
# INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
# BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
# LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
# ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.

__version__ = (0, 0, 0, "dev", 0)

from kountry import Country
from kountry import classproperty
from collections import OrderedDict


class Currency(object):
    """
    Provides the canonical representation of a currency object and
    further functionality such as querying.
    """

    _LOOKUP_TABLE = {"code": dict(), "enum": dict(), "name": dict()}
    """
    Provides a lookup table mainly for :attr:`get` class method.
    """

    DB = OrderedDict()
    """
    Provides the currency database as an ordered dictionary.
    """

    def __init__(self, code, enum, name, common_name, short_name, nickname,
                 symbol, short_symbol, decimal_points, countries):
        # Save object attributes:
        self.code = code
        self.enum = enum
        self.name = name
        self.common_name = common_name
        self.short_name = short_name
        self.nickname = nickname
        self.symbol = symbol
        self.short_symbol = short_symbol
        self.decimal_points = decimal_points
        self.countries = countries

    def __repr__(self):
        return self.name

    @classproperty
    def codes(cls):
        """
        Returns all existing currency codes.
        """
        return cls.DB.keys()

    @classmethod
    def get(cls, identifier):
        """
        Queries the :attr:`Currency.DB` for the identifier provided
        and returns the currency object if found, ``None`` otherwise.
        """
        return cls._LOOKUP_TABLE["code"].get(identifier) or \
               cls._LOOKUP_TABLE["enum"].get(identifier) or \
               cls._LOOKUP_TABLE["name"].get(identifier.upper())

    @classmethod
    def put(cls, *args):
        """
        Inserts or overrides given currencies in the DB.

        Note that this method indexes every currency by its
        :attr:`code`, :attr:`enum` and :attr:`name` attributes.
        """
        # Get the tuples by combining existing ones and new ones:
        tuples = cls.DB.items() + [(arg.code, arg) for arg in args]

        # Reset the Database:
        cls.DB = OrderedDict(sorted(tuples, key=lambda x: x[0]))

        # Reset the lookup table (code as the identifier):
        cls._LOOKUP_TABLE["code"] = dict(tuples)

        # Reset the lookup table (enum as the identifier):
        enumed_items = [(item[1].enum, item[1]) for item in tuples]
        cls._LOOKUP_TABLE["enum"] = dict(enumed_items)

        # Reset the lookup table (name as the identifier):
        named_items = [(item[1].name.upper(), item[1]) for item in tuples]
        cls._LOOKUP_TABLE["name"] = dict(named_items)

#######################
# DATABASE POPULATION #
#######################

RawData = [
    {"code": "AED",
     "name": "United Arab Emirates dirham",
     "short_name": "United Arab Emirates dirham",
     "short_symbol": "",
     "symbol": "",
     "enum": "784",
     "usage": ["AE"],
     "decimals": "2",
     "common_name": "United Arab Emirates dirham",
     "nickname": ""},
    {"code": "AFN",
     "name": "Afghan afghani",
     "short_name": "Afghan afghani",
     "short_symbol": "",
     "symbol": "",
     "enum": "971",
     "usage": ["AF"],
     "decimals": "2",
     "common_name": "Afghan afghani",
     "nickname": ""},
    {"code": "ALL",
     "name": "Albanian lek",
     "short_name": "Albanian lek",
     "short_symbol": "",
     "symbol": "",
     "enum": "008",
     "usage": ["AL"],
     "decimals": "2",
     "common_name": "Albanian lek",
     "nickname": ""},
    {"code": "AMD",
     "name": "Armenian dram",
     "short_name": "Armenian dram",
     "short_symbol": "",
     "symbol": "",
     "enum": "051",
     "usage": ["AM"],
     "decimals": "2",
     "common_name": "Armenian dram",
     "nickname": ""},
    {"code": "ANG",
     "name": "Netherlands Antillean guilder",
     "short_name": "Netherlands Antillean guilder",
     "short_symbol": "",
     "symbol": "",
     "enum": "532",
     "usage": ["CW",
               "SX"],
     "decimals": "2",
     "common_name": "Netherlands Antillean guilder",
     "nickname": ""},
    {"code": "AOA",
     "name": "Angolan kwanza",
     "short_name": "Angolan kwanza",
     "short_symbol": "",
     "symbol": "",
     "enum": "973",
     "usage": ["AO"],
     "decimals": "2",
     "common_name": "Angolan kwanza",
     "nickname": ""},
    {"code": "ARS",
     "name": "Argentine peso",
     "short_name": "Argentine peso",
     "short_symbol": "",
     "symbol": "",
     "enum": "032",
     "usage": ["AR"],
     "decimals": "2",
     "common_name": "Argentine peso",
     "nickname": ""},
    {"code": "AUD",
     "name": "Australian dollar",
     "short_name": "Australian dollar",
     "short_symbol": "",
     "symbol": "",
     "enum": "036",
     "usage": ["AU",
               "CX",
               "CC",
               "HM",
               "KI",
               "NR",
               "NF",
               "TV"],
     "decimals": "2",
     "common_name": "Australian dollar",
     "nickname": ""},
    {"code": "AWG",
     "name": "Aruban florin",
     "short_name": "Aruban florin",
     "short_symbol": "",
     "symbol": "",
     "enum": "533",
     "usage": ["AW"],
     "decimals": "2",
     "common_name": "Aruban florin",
     "nickname": ""},
    {"code": "AZN",
     "name": "Azerbaijani manat",
     "short_name": "Azerbaijani manat",
     "short_symbol": "",
     "symbol": "",
     "enum": "944",
     "usage": ["AZ"],
     "decimals": "2",
     "common_name": "Azerbaijani manat",
     "nickname": ""},
    {"code": "BAM",
     "name": "Bosnia and Herzegovina convertible mark",
     "short_name": "Bosnia and Herzegovina convertible mark",
     "short_symbol": "",
     "symbol": "",
     "enum": "977",
     "usage": ["BA"],
     "decimals": "2",
     "common_name": "Bosnia and Herzegovina convertible mark",
     "nickname": ""},
    {"code": "BBD",
     "name": "Barbados dollar",
     "short_name": "Barbados dollar",
     "short_symbol": "",
     "symbol": "",
     "enum": "052",
     "usage": ["BB"],
     "decimals": "2",
     "common_name": "Barbados dollar",
     "nickname": ""},
    {"code": "BDT",
     "name": "Bangladeshi taka",
     "short_name": "Bangladeshi taka",
     "short_symbol": "",
     "symbol": "",
     "enum": "050",
     "usage": ["BD"],
     "decimals": "2",
     "common_name": "Bangladeshi taka",
     "nickname": ""},
    {"code": "BGN",
     "name": "Bulgarian lev",
     "short_name": "Bulgarian lev",
     "short_symbol": "",
     "symbol": "",
     "enum": "975",
     "usage": ["BG"],
     "decimals": "2",
     "common_name": "Bulgarian lev",
     "nickname": ""},
    {"code": "BHD",
     "name": "Bahraini dinar",
     "short_name": "Bahraini dinar",
     "short_symbol": "",
     "symbol": "",
     "enum": "048",
     "usage": ["BH"],
     "decimals": "3",
     "common_name": "Bahraini dinar",
     "nickname": ""},
    {"code": "BIF",
     "name": "Burundian franc",
     "short_name": "Burundian franc",
     "short_symbol": "",
     "symbol": "",
     "enum": "108",
     "usage": ["BI"],
     "decimals": "0",
     "common_name": "Burundian franc",
     "nickname": ""},
    {"code": "BMD",
     "name": "Bermudian dollar (customarily known as Bermuda dollar)",
     "short_name": "Bermudian dollar (customarily known as Bermuda dollar)",
     "short_symbol": "",
     "symbol": "",
     "enum": "060",
     "usage": ["BM"],
     "decimals": "2",
     "common_name": "Bermudian dollar (customarily known as Bermuda dollar)",
     "nickname": ""},
    {"code": "BND",
     "name": "Brunei dollar",
     "short_name": "Brunei dollar",
     "short_symbol": "",
     "symbol": "",
     "enum": "096",
     "usage": ["BN",
               "SG"],
     "decimals": "2",
     "common_name": "Brunei dollar",
     "nickname": ""},
    {"code": "BOB",
     "name": "Boliviano",
     "short_name": "Boliviano",
     "short_symbol": "",
     "symbol": "",
     "enum": "068",
     "usage": ["BO"],
     "decimals": "2",
     "common_name": "Boliviano",
     "nickname": ""},
    {"code": "BOV",
     "name": "Bolivian Mvdol",
     "short_name": "Bolivian Mvdol",
     "short_symbol": "",
     "symbol": "",
     "enum": "984",
     "usage": ["BO"],
     "decimals": "2",
     "common_name": "Bolivian Mvdol",
     "nickname": ""},
    {"code": "BRL",
     "name": "Brazilian real",
     "short_name": "Brazilian real",
     "short_symbol": "",
     "symbol": "",
     "enum": "986",
     "usage": ["BR"],
     "decimals": "2",
     "common_name": "Brazilian real",
     "nickname": ""},
    {"code": "BSD",
     "name": "Bahamian dollar",
     "short_name": "Bahamian dollar",
     "short_symbol": "",
     "symbol": "",
     "enum": "044",
     "usage": ["BS"],
     "decimals": "2",
     "common_name": "Bahamian dollar",
     "nickname": ""},
    {"code": "BTN",
     "name": "Bhutanese ngultrum",
     "short_name": "Bhutanese ngultrum",
     "short_symbol": "",
     "symbol": "",
     "enum": "064",
     "usage": ["BT"],
     "decimals": "2",
     "common_name": "Bhutanese ngultrum",
     "nickname": ""},
    {"code": "BWP",
     "name": "Botswana pula",
     "short_name": "Botswana pula",
     "short_symbol": "",
     "symbol": "",
     "enum": "072",
     "usage": ["BW"],
     "decimals": "2",
     "common_name": "Botswana pula",
     "nickname": ""},
    {"code": "BYR",
     "name": "Belarusian ruble",
     "short_name": "Belarusian ruble",
     "short_symbol": "",
     "symbol": "",
     "enum": "974",
     "usage": ["BY"],
     "decimals": "0",
     "common_name": "Belarusian ruble",
     "nickname": ""},
    {"code": "BZD",
     "name": "Belize dollar",
     "short_name": "Belize dollar",
     "short_symbol": "",
     "symbol": "",
     "enum": "084",
     "usage": ["BZ"],
     "decimals": "2",
     "common_name": "Belize dollar",
     "nickname": ""},
    {"code": "CAD",
     "name": "Canadian dollar",
     "short_name": "Canadian dollar",
     "short_symbol": "",
     "symbol": "",
     "enum": "124",
     "usage": ["CA"],
     "decimals": "2",
     "common_name": "Canadian dollar",
     "nickname": ""},
    {"code": "CDF",
     "name": "Congolese franc",
     "short_name": "Congolese franc",
     "short_symbol": "",
     "symbol": "",
     "enum": "976",
     "usage": ["CD"],
     "decimals": "2",
     "common_name": "Congolese franc",
     "nickname": ""},
    {"code": "CHE",
     "name": "WIR Euro (complementary currency)",
     "short_name": "WIR Euro (complementary currency)",
     "short_symbol": "",
     "symbol": "",
     "enum": "947",
     "usage": ["CH"],
     "decimals": "2",
     "common_name": "WIR Euro (complementary currency)",
     "nickname": ""},
    {"code": "CHF",
     "name": "Swiss franc",
     "short_name": "Swiss franc",
     "short_symbol": "",
     "symbol": "",
     "enum": "756",
     "usage": ["CH",
               "LI"],
     "decimals": "2",
     "common_name": "Swiss franc",
     "nickname": ""},
    {"code": "CHW",
     "name": "WIR Franc (complementary currency)",
     "short_name": "WIR Franc (complementary currency)",
     "short_symbol": "",
     "symbol": "",
     "enum": "948",
     "usage": ["CH"],
     "decimals": "2",
     "common_name": "WIR Franc (complementary currency)",
     "nickname": ""},
    {"code": "CLF",
     "name": "Unidad de Fomento",
     "short_name": "Unidad de Fomento",
     "short_symbol": "",
     "symbol": "",
     "enum": "990",
     "usage": ["CL"],
     "decimals": "0",
     "common_name": "Unidad de Fomento",
     "nickname": ""},
    {"code": "CLP",
     "name": "Chilean peso",
     "short_name": "Chilean peso",
     "short_symbol": "",
     "symbol": "",
     "enum": "152",
     "usage": ["CL"],
     "decimals": "0",
     "common_name": "Chilean peso",
     "nickname": ""},
    {"code": "CNY",
     "name": "Chinese yuan",
     "short_name": "Chinese yuan",
     "short_symbol": "",
     "symbol": "",
     "enum": "156",
     "usage": ["CN"],
     "decimals": "2",
     "common_name": "Chinese yuan",
     "nickname": ""},
    {"code": "COP",
     "name": "Colombian peso",
     "short_name": "Colombian peso",
     "short_symbol": "",
     "symbol": "",
     "enum": "170",
     "usage": ["CO"],
     "decimals": "2",
     "common_name": "Colombian peso",
     "nickname": ""},
    {"code": "COU",
     "name": "Unidad de Valor Real",
     "short_name": "Unidad de Valor Real",
     "short_symbol": "",
     "symbol": "",
     "enum": "970",
     "usage": ["CO"],
     "decimals": "2",
     "common_name": "Unidad de Valor Real",
     "nickname": ""},
    {"code": "CRC",
     "name": "Costa Rican colon",
     "short_name": "Costa Rican colon",
     "short_symbol": "",
     "symbol": "",
     "enum": "188",
     "usage": ["CR"],
     "decimals": "2",
     "common_name": "Costa Rican colon",
     "nickname": ""},
    {"code": "CUC",
     "name": "Cuban convertible peso",
     "short_name": "Cuban convertible peso",
     "short_symbol": "",
     "symbol": "",
     "enum": "931",
     "usage": ["CU"],
     "decimals": "2",
     "common_name": "Cuban convertible peso",
     "nickname": ""},
    {"code": "CUP",
     "name": "Cuban peso",
     "short_name": "Cuban peso",
     "short_symbol": "",
     "symbol": "",
     "enum": "192",
     "usage": ["CU"],
     "decimals": "2",
     "common_name": "Cuban peso",
     "nickname": ""},
    {"code": "CVE",
     "name": "Cape Verde escudo",
     "short_name": "Cape Verde escudo",
     "short_symbol": "",
     "symbol": "",
     "enum": "132",
     "usage": ["CV"],
     "decimals": "0",
     "common_name": "Cape Verde escudo",
     "nickname": ""},
    {"code": "CZK",
     "name": "Czech koruna",
     "short_name": "Czech koruna",
     "short_symbol": "",
     "symbol": "",
     "enum": "203",
     "usage": ["CZ"],
     "decimals": "2",
     "common_name": "Czech koruna",
     "nickname": ""},
    {"code": "DJF",
     "name": "Djiboutian franc",
     "short_name": "Djiboutian franc",
     "short_symbol": "",
     "symbol": "",
     "enum": "262",
     "usage": ["DJ"],
     "decimals": "0",
     "common_name": "Djiboutian franc",
     "nickname": ""},
    {"code": "DKK",
     "name": "Danish krone",
     "short_name": "Danish krone",
     "short_symbol": "",
     "symbol": "",
     "enum": "208",
     "usage": ["DK",
               "FO",
               "GL"],
     "decimals": "2",
     "common_name": "Danish krone",
     "nickname": ""},
    {"code": "DOP",
     "name": "Dominican peso",
     "short_name": "Dominican peso",
     "short_symbol": "",
     "symbol": "",
     "enum": "214",
     "usage": ["DO"],
     "decimals": "2",
     "common_name": "Dominican peso",
     "nickname": ""},
    {"code": "DZD",
     "name": "Algerian dinar",
     "short_name": "Algerian dinar",
     "short_symbol": "",
     "symbol": "",
     "enum": "012",
     "usage": ["DZ"],
     "decimals": "2",
     "common_name": "Algerian dinar",
     "nickname": ""},
    {"code": "EGP",
     "name": "Egyptian pound",
     "short_name": "Egyptian pound",
     "short_symbol": "",
     "symbol": "",
     "enum": "818",
     "usage": ["EG"],
     "decimals": "2",
     "common_name": "Egyptian pound",
     "nickname": ""},
    {"code": "ERN",
     "name": "Eritrean nakfa",
     "short_name": "Eritrean nakfa",
     "short_symbol": "",
     "symbol": "",
     "enum": "232",
     "usage": ["ER"],
     "decimals": "2",
     "common_name": "Eritrean nakfa",
     "nickname": ""},
    {"code": "ETB",
     "name": "Ethiopian birr",
     "short_name": "Ethiopian birr",
     "short_symbol": "",
     "symbol": "",
     "enum": "230",
     "usage": ["ET"],
     "decimals": "2",
     "common_name": "Ethiopian birr",
     "nickname": ""},
    {"code": "EUR",
     "name": "Euro",
     "short_name": "Euro",
     "short_symbol": "",
     "symbol": "",
     "enum": "978",
     "usage": ["AD",
               "AT",
               "BE",
               "CY",
               "EE",
               "FI",
               "FR",
               "DE",
               "GR",
               "IE",
               "IT",
               "XK",
               "LU",
               "MT",
               "MC",
               "ME",
               "NL",
               "PT",
               "SM",
               "SK",
               "SI",
               "ES",
               "VA"],
     "decimals": "2",
     "common_name": "Euro",
     "nickname": ""},
    {"code": "FJD",
     "name": "Fiji dollar",
     "short_name": "Fiji dollar",
     "short_symbol": "",
     "symbol": "",
     "enum": "242",
     "usage": ["FJ"],
     "decimals": "2",
     "common_name": "Fiji dollar",
     "nickname": ""},
    {"code": "FKP",
     "name": "Falkland Islands pound",
     "short_name": "Falkland Islands pound",
     "short_symbol": "",
     "symbol": "",
     "enum": "238",
     "usage": ["FK"],
     "decimals": "2",
     "common_name": "Falkland Islands pound",
     "nickname": ""},
    {"code": "GBP",
     "name": "Pound sterling",
     "short_name": "Pound sterling",
     "short_symbol": "",
     "symbol": "",
     "enum": "826",
     "usage": ["GB",
               "IM",
               "GS",
               "IO"],
     "decimals": "2",
     "common_name": "Pound sterling",
     "nickname": ""},
    {"code": "GEL",
     "name": "Georgian lari",
     "short_name": "Georgian lari",
     "short_symbol": "",
     "symbol": "",
     "enum": "981",
     "usage": ["GE"],
     "decimals": "2",
     "common_name": "Georgian lari",
     "nickname": ""},
    {"code": "GHS",
     "name": "Ghanaian cedi",
     "short_name": "Ghanaian cedi",
     "short_symbol": "",
     "symbol": "",
     "enum": "936",
     "usage": ["GH"],
     "decimals": "2",
     "common_name": "Ghanaian cedi",
     "nickname": ""},
    {"code": "GIP",
     "name": "Gibraltar pound",
     "short_name": "Gibraltar pound",
     "short_symbol": "",
     "symbol": "",
     "enum": "292",
     "usage": ["GI"],
     "decimals": "2",
     "common_name": "Gibraltar pound",
     "nickname": ""},
    {"code": "GMD",
     "name": "Gambian dalasi",
     "short_name": "Gambian dalasi",
     "short_symbol": "",
     "symbol": "",
     "enum": "270",
     "usage": ["GM"],
     "decimals": "2",
     "common_name": "Gambian dalasi",
     "nickname": ""},
    {"code": "GNF",
     "name": "Guinean franc",
     "short_name": "Guinean franc",
     "short_symbol": "",
     "symbol": "",
     "enum": "324",
     "usage": ["GN"],
     "decimals": "0",
     "common_name": "Guinean franc",
     "nickname": ""},
    {"code": "GTQ",
     "name": "Guatemalan quetzal",
     "short_name": "Guatemalan quetzal",
     "short_symbol": "",
     "symbol": "",
     "enum": "320",
     "usage": ["GT"],
     "decimals": "2",
     "common_name": "Guatemalan quetzal",
     "nickname": ""},
    {"code": "GYD",
     "name": "Guyanese dollar",
     "short_name": "Guyanese dollar",
     "short_symbol": "",
     "symbol": "",
     "enum": "328",
     "usage": ["GY"],
     "decimals": "2",
     "common_name": "Guyanese dollar",
     "nickname": ""},
    {"code": "HKD",
     "name": "Hong Kong dollar",
     "short_name": "Hong Kong dollar",
     "short_symbol": "",
     "symbol": "",
     "enum": "344",
     "usage": ["HK",
               "MO"],
     "decimals": "2",
     "common_name": "Hong Kong dollar",
     "nickname": ""},
    {"code": "HNL",
     "name": "Honduran lempira",
     "short_name": "Honduran lempira",
     "short_symbol": "",
     "symbol": "",
     "enum": "340",
     "usage": ["HN"],
     "decimals": "2",
     "common_name": "Honduran lempira",
     "nickname": ""},
    {"code": "HRK",
     "name": "Croatian kuna",
     "short_name": "Croatian kuna",
     "short_symbol": "",
     "symbol": "",
     "enum": "191",
     "usage": ["HR"],
     "decimals": "2",
     "common_name": "Croatian kuna",
     "nickname": ""},
    {"code": "HTG",
     "name": "Haitian gourde",
     "short_name": "Haitian gourde",
     "short_symbol": "",
     "symbol": "",
     "enum": "332",
     "usage": ["HT"],
     "decimals": "2",
     "common_name": "Haitian gourde",
     "nickname": ""},
    {"code": "HUF",
     "name": "Hungarian forint",
     "short_name": "Hungarian forint",
     "short_symbol": "",
     "symbol": "",
     "enum": "348",
     "usage": ["HU"],
     "decimals": "2",
     "common_name": "Hungarian forint",
     "nickname": ""},
    {"code": "IDR",
     "name": "Indonesian rupiah",
     "short_name": "Indonesian rupiah",
     "short_symbol": "",
     "symbol": "",
     "enum": "360",
     "usage": ["ID"],
     "decimals": "2",
     "common_name": "Indonesian rupiah",
     "nickname": ""},
    {"code": "ILS",
     "name": "Israeli new sheqel",
     "short_name": "Israeli new sheqel",
     "short_symbol": "",
     "symbol": "",
     "enum": "376",
     "usage": ["IL",
               "PS"],
     "decimals": "2",
     "common_name": "Israeli new sheqel",
     "nickname": ""},
    {"code": "INR",
     "name": "Indian rupee",
     "short_name": "Indian rupee",
     "short_symbol": "",
     "symbol": "",
     "enum": "356",
     "usage": ["IN"],
     "decimals": "2",
     "common_name": "Indian rupee",
     "nickname": ""},
    {"code": "IQD",
     "name": "Iraqi dinar",
     "short_name": "Iraqi dinar",
     "short_symbol": "",
     "symbol": "",
     "enum": "368",
     "usage": ["IQ"],
     "decimals": "3",
     "common_name": "Iraqi dinar",
     "nickname": ""},
    {"code": "IRR",
     "name": "Iranian rial",
     "short_name": "Iranian rial",
     "short_symbol": "",
     "symbol": "",
     "enum": "364",
     "usage": ["IR"],
     "decimals": "0",
     "common_name": "Iranian rial",
     "nickname": ""},
    {"code": "ISK",
     "name": "Icelandic króna",
     "short_name": "Icelandic króna",
     "short_symbol": "",
     "symbol": "",
     "enum": "352",
     "usage": ["IS"],
     "decimals": "0",
     "common_name": "Icelandic króna",
     "nickname": ""},
    {"code": "JMD",
     "name": "Jamaican dollar",
     "short_name": "Jamaican dollar",
     "short_symbol": "",
     "symbol": "",
     "enum": "388",
     "usage": ["JM"],
     "decimals": "2",
     "common_name": "Jamaican dollar",
     "nickname": ""},
    {"code": "JOD",
     "name": "Jordanian dinar",
     "short_name": "Jordanian dinar",
     "short_symbol": "",
     "symbol": "",
     "enum": "400",
     "usage": ["JO"],
     "decimals": "3",
     "common_name": "Jordanian dinar",
     "nickname": ""},
    {"code": "JPY",
     "name": "Japanese yen",
     "short_name": "Japanese yen",
     "short_symbol": "",
     "symbol": "",
     "enum": "392",
     "usage": ["JP"],
     "decimals": "0",
     "common_name": "Japanese yen",
     "nickname": ""},
    {"code": "KES",
     "name": "Kenyan shilling",
     "short_name": "Kenyan shilling",
     "short_symbol": "",
     "symbol": "",
     "enum": "404",
     "usage": ["KE"],
     "decimals": "2",
     "common_name": "Kenyan shilling",
     "nickname": ""},
    {"code": "KGS",
     "name": "Kyrgyzstani som",
     "short_name": "Kyrgyzstani som",
     "short_symbol": "",
     "symbol": "",
     "enum": "417",
     "usage": ["KG"],
     "decimals": "2",
     "common_name": "Kyrgyzstani som",
     "nickname": ""},
    {"code": "KHR",
     "name": "Cambodian riel",
     "short_name": "Cambodian riel",
     "short_symbol": "",
     "symbol": "",
     "enum": "116",
     "usage": ["KH"],
     "decimals": "2",
     "common_name": "Cambodian riel",
     "nickname": ""},
    {"code": "KMF",
     "name": "Comoro franc",
     "short_name": "Comoro franc",
     "short_symbol": "",
     "symbol": "",
     "enum": "174",
     "usage": ["KM"],
     "decimals": "0",
     "common_name": "Comoro franc",
     "nickname": ""},
    {"code": "KPW",
     "name": "North Korean won",
     "short_name": "North Korean won",
     "short_symbol": "",
     "symbol": "",
     "enum": "408",
     "usage": ["KP"],
     "decimals": "0",
     "common_name": "North Korean won",
     "nickname": ""},
    {"code": "KRW",
     "name": "South Korean won",
     "short_name": "South Korean won",
     "short_symbol": "",
     "symbol": "",
     "enum": "410",
     "usage": ["KR"],
     "decimals": "0",
     "common_name": "South Korean won",
     "nickname": ""},
    {"code": "KWD",
     "name": "Kuwaiti dinar",
     "short_name": "Kuwaiti dinar",
     "short_symbol": "",
     "symbol": "",
     "enum": "414",
     "usage": ["KW"],
     "decimals": "3",
     "common_name": "Kuwaiti dinar",
     "nickname": ""},
    {"code": "KYD",
     "name": "Cayman Islands dollar",
     "short_name": "Cayman Islands dollar",
     "short_symbol": "",
     "symbol": "",
     "enum": "136",
     "usage": ["KY"],
     "decimals": "2",
     "common_name": "Cayman Islands dollar",
     "nickname": ""},
    {"code": "KZT",
     "name": "Kazakhstani tenge",
     "short_name": "Kazakhstani tenge",
     "short_symbol": "",
     "symbol": "",
     "enum": "398",
     "usage": ["KZ"],
     "decimals": "2",
     "common_name": "Kazakhstani tenge",
     "nickname": ""},
    {"code": "LAK",
     "name": "Lao kip",
     "short_name": "Lao kip",
     "short_symbol": "",
     "symbol": "",
     "enum": "418",
     "usage": ["LA"],
     "decimals": "0",
     "common_name": "Lao kip",
     "nickname": ""},
    {"code": "LBP",
     "name": "Lebanese pound",
     "short_name": "Lebanese pound",
     "short_symbol": "",
     "symbol": "",
     "enum": "422",
     "usage": ["LB"],
     "decimals": "0",
     "common_name": "Lebanese pound",
     "nickname": ""},
    {"code": "LKR",
     "name": "Sri Lankan rupee",
     "short_name": "Sri Lankan rupee",
     "short_symbol": "",
     "symbol": "",
     "enum": "144",
     "usage": ["LK"],
     "decimals": "2",
     "common_name": "Sri Lankan rupee",
     "nickname": ""},
    {"code": "LRD",
     "name": "Liberian dollar",
     "short_name": "Liberian dollar",
     "short_symbol": "",
     "symbol": "",
     "enum": "430",
     "usage": ["LR"],
     "decimals": "2",
     "common_name": "Liberian dollar",
     "nickname": ""},
    {"code": "LSL",
     "name": "Lesotho loti",
     "short_name": "Lesotho loti",
     "short_symbol": "",
     "symbol": "",
     "enum": "426",
     "usage": ["LS"],
     "decimals": "2",
     "common_name": "Lesotho loti",
     "nickname": ""},
    {"code": "LTL",
     "name": "Lithuanian litas",
     "short_name": "Lithuanian litas",
     "short_symbol": "",
     "symbol": "",
     "enum": "440",
     "usage": ["LT"],
     "decimals": "2",
     "common_name": "Lithuanian litas",
     "nickname": ""},
    {"code": "LVL",
     "name": "Latvian lats",
     "short_name": "Latvian lats",
     "short_symbol": "",
     "symbol": "",
     "enum": "428",
     "usage": ["LV"],
     "decimals": "2",
     "common_name": "Latvian lats",
     "nickname": ""},
    {"code": "LYD",
     "name": "Libyan dinar",
     "short_name": "Libyan dinar",
     "short_symbol": "",
     "symbol": "",
     "enum": "434",
     "usage": ["LY"],
     "decimals": "3",
     "common_name": "Libyan dinar",
     "nickname": ""},
    {"code": "MAD",
     "name": "Moroccan dirham",
     "short_name": "Moroccan dirham",
     "short_symbol": "",
     "symbol": "",
     "enum": "504",
     "usage": ["MA"],
     "decimals": "2",
     "common_name": "Moroccan dirham",
     "nickname": ""},
    {"code": "MDL",
     "name": "Moldovan leu",
     "short_name": "Moldovan leu",
     "short_symbol": "",
     "symbol": "",
     "enum": "498",
     "usage": ["MD"],
     "decimals": "2",
     "common_name": "Moldovan leu",
     "nickname": ""},
    {"code": "MGA",
     "name": "Malagasy ariary",
     "short_name": "Malagasy ariary",
     "short_symbol": "",
     "symbol": "",
     "enum": "969",
     "usage": ["MG"],
     "decimals": "",
     "common_name": "Malagasy ariary",
     "nickname": ""},
    {"code": "MKD",
     "name": "Macedonian denar",
     "short_name": "Macedonian denar",
     "short_symbol": "",
     "symbol": "",
     "enum": "807",
     "usage": ["MK"],
     "decimals": "2",
     "common_name": "Macedonian denar",
     "nickname": ""},
    {"code": "MMK",
     "name": "Myanma kyat",
     "short_name": "Myanma kyat",
     "short_symbol": "",
     "symbol": "",
     "enum": "104",
     "usage": ["MM"],
     "decimals": "0",
     "common_name": "Myanma kyat",
     "nickname": ""},
    {"code": "MNT",
     "name": "Mongolian tugrik",
     "short_name": "Mongolian tugrik",
     "short_symbol": "",
     "symbol": "",
     "enum": "496",
     "usage": ["MN"],
     "decimals": "2",
     "common_name": "Mongolian tugrik",
     "nickname": ""},
    {"code": "MOP",
     "name": "Macanese pataca",
     "short_name": "Macanese pataca",
     "short_symbol": "",
     "symbol": "",
     "enum": "446",
     "usage": ["MO"],
     "decimals": "2",
     "common_name": "Macanese pataca",
     "nickname": ""},
    {"code": "MRO",
     "name": "Mauritanian ouguiya",
     "short_name": "Mauritanian ouguiya",
     "short_symbol": "",
     "symbol": "",
     "enum": "478",
     "usage": ["MR"],
     "decimals": "",
     "common_name": "Mauritanian ouguiya",
     "nickname": ""},
    {"code": "MUR",
     "name": "Mauritian rupee",
     "short_name": "Mauritian rupee",
     "short_symbol": "",
     "symbol": "",
     "enum": "480",
     "usage": ["MU"],
     "decimals": "2",
     "common_name": "Mauritian rupee",
     "nickname": ""},
    {"code": "MVR",
     "name": "Maldivian rufiyaa",
     "short_name": "Maldivian rufiyaa",
     "short_symbol": "",
     "symbol": "",
     "enum": "462",
     "usage": ["MV"],
     "decimals": "2",
     "common_name": "Maldivian rufiyaa",
     "nickname": ""},
    {"code": "MWK",
     "name": "Malawian kwacha",
     "short_name": "Malawian kwacha",
     "short_symbol": "",
     "symbol": "",
     "enum": "454",
     "usage": ["MW"],
     "decimals": "2",
     "common_name": "Malawian kwacha",
     "nickname": ""},
    {"code": "MXN",
     "name": "Mexican peso",
     "short_name": "Mexican peso",
     "short_symbol": "",
     "symbol": "",
     "enum": "484",
     "usage": ["MX"],
     "decimals": "2",
     "common_name": "Mexican peso",
     "nickname": ""},
    {"code": "MXV",
     "name": "Mexican Unidad de Inversion (UDI)",
     "short_name": "Mexican Unidad de Inversion (UDI)",
     "short_symbol": "",
     "symbol": "",
     "enum": "979",
     "usage": ["MX"],
     "decimals": "2",
     "common_name": "Mexican Unidad de Inversion (UDI)",
     "nickname": ""
     },
    {"code": "MYR",
     "name": "Malaysian ringgit",
     "short_name": "Malaysian ringgit",
     "short_symbol": "",
     "symbol": "",
     "enum": "458",
     "usage": ["MY"],
     "decimals": "2",
     "common_name": "Malaysian ringgit",
     "nickname": ""},
    {"code": "MZN",
     "name": "Mozambican metical",
     "short_name": "Mozambican metical",
     "short_symbol": "",
     "symbol": "",
     "enum": "943",
     "usage": ["MZ"],
     "decimals": "2",
     "common_name": "Mozambican metical",
     "nickname": ""},
    {"code": "NAD",
     "name": "Namibian dollar",
     "short_name": "Namibian dollar",
     "short_symbol": "",
     "symbol": "",
     "enum": "516",
     "usage": ["NA"
               ],
     "decimals": "2",
     "common_name": "Namibian dollar",
     "nickname": ""},
    {"code": "NGN",
     "name": "Nigerian naira",
     "short_name": "Nigerian naira",
     "short_symbol": "",
     "symbol": "",
     "enum": "566",
     "usage": ["NG"
               ],
     "decimals": "2",
     "common_name": "Nigerian naira",
     "nickname": ""},
    {"code": "NIO",
     "name": "Nicaraguan córdoba",
     "short_name": "Nicaraguan córdoba",
     "short_symbol": "",
     "symbol": "",
     "enum": "558",
     "usage": [
         "NI"],
     "decimals": "2",
     "common_name": "Nicaraguan córdoba",
     "nickname": ""},
    {"code": "NOK",
     "name": "Norwegian krone",
     "short_name": "Norwegian krone",
     "short_symbol": "",
     "symbol": "",
     "enum": "578",
     "usage": ["NO",
               "SJ",
               "BV"],
     "decimals": "2",
     "common_name": "Norwegian krone",
     "nickname": ""},
    {"code": "NPR",
     "name": "Nepalese rupee",
     "short_name": "Nepalese rupee",
     "short_symbol": "",
     "symbol": "",
     "enum": "524",
     "usage": ["NP"],
     "decimals": "2",
     "common_name": "Nepalese rupee",
     "nickname": ""},
    {"code": "NZD",
     "name": "New Zealand dollar",
     "short_name": "New Zealand dollar",
     "short_symbol": "",
     "symbol": "",
     "enum": "554",
     "usage": ["CK",
               "NZ",
               "NU",
               "PN",
               "TK"],
     "decimals": "2",
     "common_name": "New Zealand dollar",
     "nickname": ""},
    {"code": "OMR",
     "name": "Omani rial",
     "short_name": "Omani rial",
     "short_symbol": "",
     "symbol": "",
     "enum": "512",
     "usage": ["OM"],
     "decimals": "3",
     "common_name": "Omani rial",
     "nickname": ""},
    {"code": "PAB",
     "name": "Panamanian balboa",
     "short_name": "Panamanian balboa",
     "short_symbol": "",
     "symbol": "",
     "enum": "590",
     "usage": ["PA"],
     "decimals": "2",
     "common_name": "Panamanian balboa",
     "nickname": ""},
    {"code": "PEN",
     "name": "Peruvian nuevo sol",
     "short_name": "Peruvian nuevo sol",
     "short_symbol": "",
     "symbol": "",
     "enum": "604",
     "usage": ["PE"],
     "decimals": "2",
     "common_name": "Peruvian nuevo sol",
     "nickname": ""},
    {"code": "PGK",
     "name": "Papua New Guinean kina",
     "short_name": "Papua New Guinean kina",
     "short_symbol": "",
     "symbol": "",
     "enum": "598",
     "usage": ["PG"],
     "decimals": "2",
     "common_name": "Papua New Guinean kina",
     "nickname": ""},
    {"code": "PHP",
     "name": "Philippine peso",
     "short_name": "Philippine peso",
     "short_symbol": "",
     "symbol": "",
     "enum": "608",
     "usage": ["PH"],
     "decimals": "2",
     "common_name": "Philippine peso",
     "nickname": ""},
    {"code": "PKR",
     "name": "Pakistani rupee",
     "short_name": "Pakistani rupee",
     "short_symbol": "",
     "symbol": "",
     "enum": "586",
     "usage": ["PK"],
     "decimals": "2",
     "common_name": "Pakistani rupee",
     "nickname": ""},
    {"code": "PLN",
     "name": "Polish złoty",
     "short_name": "Polish złoty",
     "short_symbol": "",
     "symbol": "",
     "enum": "985",
     "usage": ["PL"],
     "decimals": "2",
     "common_name": "Polish złoty",
     "nickname": ""},
    {"code": "PYG",
     "name": "Paraguayan guaraní",
     "short_name": "Paraguayan guaraní",
     "short_symbol": "",
     "symbol": "",
     "enum": "600",
     "usage": ["PY"],
     "decimals": "0",
     "common_name": "Paraguayan guaraní",
     "nickname": ""},
    {"code": "QAR",
     "name": "Qatari riyal",
     "short_name": "Qatari riyal",
     "short_symbol": "",
     "symbol": "",
     "enum": "634",
     "usage": ["QA"],
     "decimals": "2",
     "common_name": "Qatari riyal",
     "nickname": ""},
    {"code": "RON",
     "name": "Romanian new leu",
     "short_name": "Romanian new leu",
     "short_symbol": "",
     "symbol": "",
     "enum": "946",
     "usage": ["RO"],
     "decimals": "2",
     "common_name": "Romanian new leu",
     "nickname": ""},
    {"code": "RSD",
     "name": "Serbian dinar",
     "short_name": "Serbian dinar",
     "short_symbol": "",
     "symbol": "",
     "enum": "941",
     "usage": ["RS"],
     "decimals": "2",
     "common_name": "Serbian dinar",
     "nickname": ""},
    {"code": "RUB",
     "name": "Russian rouble",
     "short_name": "Russian rouble",
     "short_symbol": "",
     "symbol": "",
     "enum": "643",
     "usage": ["RU"],
     "decimals": "2",
     "common_name": "Russian rouble",
     "nickname": ""},
    {"code": "RWF",
     "name": "Rwandan franc",
     "short_name": "Rwandan franc",
     "short_symbol": "",
     "symbol": "",
     "enum": "646",
     "usage": ["RW"],
     "decimals": "0",
     "common_name": "Rwandan franc",
     "nickname": ""},
    {"code": "SAR",
     "name": "Saudi riyal",
     "short_name": "Saudi riyal",
     "short_symbol": "",
     "symbol": "",
     "enum": "682",
     "usage": ["SA"],
     "decimals": "2",
     "common_name": "Saudi riyal",
     "nickname": ""},
    {"code": "SBD",
     "name": "Solomon Islands dollar",
     "short_name": "Solomon Islands dollar",
     "short_symbol": "",
     "symbol": "",
     "enum": "090",
     "usage": ["SB"],
     "decimals": "2",
     "common_name": "Solomon Islands dollar",
     "nickname": ""},
    {"code": "SCR",
     "name": "Seychelles rupee",
     "short_name": "Seychelles rupee",
     "short_symbol": "",
     "symbol": "",
     "enum": "690",
     "usage": ["SC"],
     "decimals": "2",
     "common_name": "Seychelles rupee",
     "nickname": ""},
    {"code": "SDG",
     "name": "Sudanese pound",
     "short_name": "Sudanese pound",
     "short_symbol": "",
     "symbol": "",
     "enum": "938",
     "usage": ["SD"],
     "decimals": "2",
     "common_name": "Sudanese pound",
     "nickname": ""},
    {"code": "SEK",
     "name": "Swedish krona/kronor",
     "short_name": "Swedish krona/kronor",
     "short_symbol": "",
     "symbol": "",
     "enum": "752",
     "usage": ["SE"],
     "decimals": "2",
     "common_name": "Swedish krona/kronor",
     "nickname": ""},
    {"code": "SGD",
     "name": "Singapore dollar",
     "short_name": "Singapore dollar",
     "short_symbol": "",
     "symbol": "",
     "enum": "702",
     "usage": ["SG",
               "BN"],
     "decimals": "2",
     "common_name": "Singapore dollar",
     "nickname": ""},
    {"code": "SHP",
     "name": "Saint Helena pound",
     "short_name": "Saint Helena pound",
     "short_symbol": "",
     "symbol": "",
     "enum": "654",
     "usage": ["SH"],
     "decimals": "2",
     "common_name": "Saint Helena pound",
     "nickname": ""},
    {"code": "SLL",
     "name": "Sierra Leonean leone",
     "short_name": "Sierra Leonean leone",
     "short_symbol": "",
     "symbol": "",
     "enum": "694",
     "usage": ["SL"],
     "decimals": "0",
     "common_name": "Sierra Leonean leone",
     "nickname": ""},
    {"code": "SOS",
     "name": "Somali shilling",
     "short_name": "Somali shilling",
     "short_symbol": "",
     "symbol": "",
     "enum": "706",
     "usage": ["SO"],
     "decimals": "2",
     "common_name": "Somali shilling",
     "nickname": ""},
    {"code": "SRD",
     "name": "Surinamese dollar",
     "short_name": "Surinamese dollar",
     "short_symbol": "",
     "symbol": "",
     "enum": "968",
     "usage": ["SR"],
     "decimals": "2",
     "common_name": "Surinamese dollar",
     "nickname": ""},
    {"code": "SSP",
     "name": "South Sudanese pound",
     "short_name": "South Sudanese pound",
     "short_symbol": "",
     "symbol": "",
     "enum": "728",
     "usage": ["SS"],
     "decimals": "2",
     "common_name": "South Sudanese pound",
     "nickname": ""},
    {"code": "STD",
     "name": "São Tomé and Príncipe dobra",
     "short_name": "São Tomé and Príncipe dobra",
     "short_symbol": "",
     "symbol": "",
     "enum": "678",
     "usage": ["ST"],
     "decimals": "0",
     "common_name": "São Tomé and Príncipe dobra",
     "nickname": ""},
    {"code": "SYP",
     "name": "Syrian pound",
     "short_name": "Syrian pound",
     "short_symbol": "",
     "symbol": "",
     "enum": "760",
     "usage": ["SY"],
     "decimals": "2",
     "common_name": "Syrian pound",
     "nickname": ""},
    {"code": "SZL",
     "name": "Swazi lilangeni",
     "short_name": "Swazi lilangeni",
     "short_symbol": "",
     "symbol": "",
     "enum": "748",
     "usage": ["SZ"],
     "decimals": "2",
     "common_name": "Swazi lilangeni",
     "nickname": ""},
    {"code": "THB",
     "name": "Thai baht",
     "short_name": "Thai baht",
     "short_symbol": "",
     "symbol": "",
     "enum": "764",
     "usage": ["TH"],
     "decimals": "2",
     "common_name": "Thai baht",
     "nickname": ""},
    {"code": "TJS",
     "name": "Tajikistani somoni",
     "short_name": "Tajikistani somoni",
     "short_symbol": "",
     "symbol": "",
     "enum": "972",
     "usage": ["TJ"],
     "decimals": "2",
     "common_name": "Tajikistani somoni",
     "nickname": ""},
    {"code": "TMT",
     "name": "Turkmenistani manat",
     "short_name": "Turkmenistani manat",
     "short_symbol": "",
     "symbol": "",
     "enum": "934",
     "usage": ["TM"],
     "decimals": "2",
     "common_name": "Turkmenistani manat",
     "nickname": ""},
    {"code": "TND",
     "name": "Tunisian dinar",
     "short_name": "Tunisian dinar",
     "short_symbol": "",
     "symbol": "",
     "enum": "788",
     "usage": ["TN"],
     "decimals": "3",
     "common_name": "Tunisian dinar",
     "nickname": ""},
    {"code": "TOP",
     "name": "Tongan paʻanga",
     "short_name": "Tongan paʻanga",
     "short_symbol": "",
     "symbol": "",
     "enum": "776",
     "usage": ["TO"],
     "decimals": "2",
     "common_name": "Tongan paʻanga",
     "nickname": ""},
    {"code": "TRY",
     "name": "Turkish lira",
     "short_name": "Turkish lira",
     "short_symbol": "",
     "symbol": "",
     "enum": "949",
     "usage": ["TR"],
     "decimals": "2",
     "common_name": "Turkish lira",
     "nickname": ""},
    {"code": "TTD",
     "name": "Trinidad and Tobago dollar",
     "short_name": "Trinidad and Tobago dollar",
     "short_symbol": "",
     "symbol": "",
     "enum": "780",
     "usage": ["TT"],
     "decimals": "2",
     "common_name": "Trinidad and Tobago dollar",
     "nickname": ""},
    {"code": "TWD",
     "name": "New Taiwan dollar",
     "short_name": "New Taiwan dollar",
     "short_symbol": "",
     "symbol": "",
     "enum": "901",
     "usage": ["TW"],
     "decimals": "2",
     "common_name": "New Taiwan dollar",
     "nickname": ""},
    {"code": "TZS",
     "name": "Tanzanian shilling",
     "short_name": "Tanzanian shilling",
     "short_symbol": "",
     "symbol": "",
     "enum": "834",
     "usage": ["TZ"],
     "decimals": "2",
     "common_name": "Tanzanian shilling",
     "nickname": ""},
    {"code": "UAH",
     "name": "Ukrainian hryvnia",
     "short_name": "Ukrainian hryvnia",
     "short_symbol": "",
     "symbol": "",
     "enum": "980",
     "usage": ["UA"],
     "decimals": "2",
     "common_name": "Ukrainian hryvnia",
     "nickname": ""},
    {"code": "UGX",
     "name": "Ugandan shilling",
     "short_name": "Ugandan shilling",
     "short_symbol": "",
     "symbol": "",
     "enum": "800",
     "usage": ["UG"],
     "decimals": "2",
     "common_name": "Ugandan shilling",
     "nickname": ""},
    {"code": "USD",
     "name": "United States dollar",
     "short_name": "United States dollar",
     "short_symbol": "",
     "symbol": "",
     "enum": "840",
     "usage": ["AS",
               "BB",
               "BM",
               "IO",
               "VG",
               "EC",
               "SV",
               "GU",
               "HT",
               "MH",
               "FM",
               "MP",
               "PW",
               "PA",
               "PR",
               "TC",
               "US",
               "VI",
               "ZW"],
     "decimals": "2",
     "common_name": "United States dollar",
     "nickname": ""},
    {"code": "USN",
     "name": "United States dollar (next day)",
     "short_name": "United States dollar (next day)",
     "short_symbol": "",
     "symbol": "",
     "enum": "997",
     "usage": ["US"],
     "decimals": "2",
     "common_name": "United States dollar (next day)",
     "nickname": ""},
    {"code": "USS",
     "name": "United States dollar (same day)",
     "short_name": "United States dollar (same day)",
     "short_symbol": "",
     "symbol": "",
     "enum": "998",
     "usage": ["US"],
     "decimals": "2",
     "common_name": "United States dollar (same day)",
     "nickname": ""},
    {"code": "UYI",
     "name": "Uruguay Peso en Unidades Indexadas (URUIURUI)",
     "short_name": "Uruguay Peso en Unidades Indexadas (URUIURUI)",
     "short_symbol": "",
     "symbol": "",
     "enum": "940",
     "usage": ["UY"],
     "decimals": "0",
     "common_name": "Uruguay Peso en Unidades Indexadas (URUIURUI)",
     "nickname": ""},
    {"code": "UYU",
     "name": "Uruguayan peso",
     "short_name": "Uruguayan peso",
     "short_symbol": "",
     "symbol": "",
     "enum": "858",
     "usage": ["UY"],
     "decimals": "2",
     "common_name": "Uruguayan peso",
     "nickname": ""},
    {"code": "UZS",
     "name": "Uzbekistan som",
     "short_name": "Uzbekistan som",
     "short_symbol": "",
     "symbol": "",
     "enum": "860",
     "usage": ["UZ"],
     "decimals": "2",
     "common_name": "Uzbekistan som",
     "nickname": ""},
    {"code": "VEF",
     "name": "Venezuelan bolívar fuerte",
     "short_name": "Venezuelan bolívar fuerte",
     "short_symbol": "",
     "symbol": "",
     "enum": "937",
     "usage": ["VE"],
     "decimals": "2",
     "common_name": "Venezuelan bolívar fuerte",
     "nickname": ""},
    {"code": "VND",
     "name": "Vietname dong",
     "short_name": "Vietname dong",
     "short_symbol": "",
     "symbol": "",
     "enum": "704",
     "usage": ["VN"],
     "decimals": "0",
     "common_name": "Vietname dong",
     "nickname": ""},
    {"code": "VUV",
     "name": "Vanuatu vatu",
     "short_name": "Vanuatu vatu",
     "short_symbol": "",
     "symbol": "",
     "enum": "548",
     "usage": ["VU"],
     "decimals": "0",
     "common_name": "Vanuatu vatu",
     "nickname": ""},
    {"code": "WST",
     "name": "Samoan tala",
     "short_name": "Samoan tala",
     "short_symbol": "",
     "symbol": "",
     "enum": "882",
     "usage": ["WS"],
     "decimals": "2",
     "common_name": "Samoan tala",
     "nickname": ""},
    {"code": "XAF",
     "name": "CFA franc BEAC",
     "short_name": "CFA franc BEAC",
     "short_symbol": "",
     "symbol": "",
     "enum": "950",
     "usage": ["CM",
               "CF",
               "CG",
               "TD",
               "GQ",
               "GA"],
     "decimals": "0",
     "common_name": "CFA franc BEAC",
     "nickname": ""},
    {"code": "XAG",
     "name": "Silver (one troy ounce)",
     "short_name": "Silver (one troy ounce)",
     "short_symbol": "",
     "symbol": "",
     "enum": "961",
     "usage": [],
     "decimals": "0",
     "common_name": "Silver (one troy ounce)",
     "nickname": ""},
    {"code": "XAU",
     "name": "Gold (one troy ounce)",
     "short_name": "Gold (one troy ounce)",
     "short_symbol": "",
     "symbol": "",
     "enum": "959",
     "usage": [],
     "decimals": "0",
     "common_name": "Gold (one troy ounce)",
     "nickname": ""},
    {"code": "XBA",
     "name": "European Composite Unit (EURCO)",
     "short_name": "European Composite Unit (EURCO)",
     "short_symbol": "",
     "symbol": "",
     "enum": "955",
     "usage": [],
     "decimals": "0",
     "common_name": "European Composite Unit (EURCO)",
     "nickname": ""},
    {"code": "XBB",
     "name": "European Monetary Unit (E.M.U.-6)",
     "short_name": "European Monetary Unit (E.M.U.-6)",
     "short_symbol": "",
     "symbol": "",
     "enum": "956",
     "usage": [],
     "decimals": "0",
     "common_name": "European Monetary Unit (E.M.U.-6)",
     "nickname": ""},
    {"code": "XBC",
     "name": "European Unit of Account 9 (E.U.A.-9)",
     "short_name": "European Unit of Account 9 (E.U.A.-9)",
     "short_symbol": "",
     "symbol": "",
     "enum": "957",
     "usage": [],
     "decimals": "0",
     "common_name": "European Unit of Account 9 (E.U.A.-9)",
     "nickname": ""},
    {"code": "XBD",
     "name": "European Unit of Account 17 (E.U.A.-17)",
     "short_name": "European Unit of Account 17 (E.U.A.-17)",
     "short_symbol": "",
     "symbol": "",
     "enum": "958",
     "usage": [],
     "decimals": "0",
     "common_name": "European Unit of Account 17 (E.U.A.-17)",
     "nickname": ""},
    {"code": "XCD",
     "name": "East Caribbean dollar",
     "short_name": "East Caribbean dollar",
     "short_symbol": "",
     "symbol": "",
     "enum": "951",
     "usage": ["AI",
               "AG",
               "DM",
               "GD",
               "MS",
               "KN",
               "LC",
               "VC"],
     "decimals": "2",
     "common_name": "East Caribbean dollar",
     "nickname": ""},
    {"code": "XDR",
     "name": "Special drawing rights",
     "short_name": "Special drawing rights",
     "short_symbol": "",
     "symbol": "",
     "enum": "960",
     "usage": [],
     "decimals": "0",
     "common_name": "Special drawing rights",
     "nickname": ""},
    {"code": "XFU",
     "name": "UIC franc (special settlement currency)",
     "short_name": "UIC franc (special settlement currency)",
     "short_symbol": "",
     "symbol": "",
     "enum": "None",
     "usage": [],
     "decimals": "0",
     "common_name": "UIC franc (special settlement currency)",
     "nickname": ""},
    {"code": "XOF",
     "name": "CFA Franc BCEAO",
     "short_name": "CFA Franc BCEAO",
     "short_symbol": "",
     "symbol": "",
     "enum": "952",
     "usage": ["BJ",
               "BF",
               "GW",
               "ML",
               "NE",
               "SN",
               "TG"],
     "decimals": "0",
     "common_name": "CFA Franc BCEAO",
     "nickname": ""},
    {"code": "XPD",
     "name": "Palladium (one troy ounce)",
     "short_name": "Palladium (one troy ounce)",
     "short_symbol": "",
     "symbol": "",
     "enum": "964",
     "usage": [],
     "decimals": "0",
     "common_name": "Palladium (one troy ounce)",
     "nickname": ""},
    {"code": "XPF",
     "name": "CFP franc",
     "short_name": "CFP franc",
     "short_symbol": "",
     "symbol": "",
     "enum": "953",
     "usage": ["PF",
               "NC",
               "WF"],
     "decimals": "0",
     "common_name": "CFP franc",
     "nickname": ""},
    {"code": "XPT",
     "name": "Platinum (one troy ounce)",
     "short_name": "Platinum (one troy ounce)",
     "short_symbol": "",
     "symbol": "",
     "enum": "962",
     "usage": [],
     "decimals": "0",
     "common_name": "Platinum (one troy ounce)",
     "nickname": ""},
    {"code": "XTS",
     "name": "Code reserved for testing purposes",
     "short_name": "Code reserved for testing purposes",
     "short_symbol": "",
     "symbol": "",
     "enum": "963",
     "usage": [],
     "decimals": "0",
     "common_name": "Code reserved for testing purposes",
     "nickname": ""},
    {"code": "XXX",
     "name": "No currency",
     "short_name": "No currency",
     "short_symbol": "",
     "symbol": "",
     "enum": "999",
     "usage": [],
     "decimals": "0",
     "common_name": "No currency",
     "nickname": ""},
    {"code": "YER",
     "name": "Yemeni rial",
     "short_name": "Yemeni rial",
     "short_symbol": "",
     "symbol": "",
     "enum": "886",
     "usage": ["YE"],
     "decimals": "2",
     "common_name": "Yemeni rial",
     "nickname": ""},
    {"code": "ZAR",
     "name": "South African rand",
     "short_name": "South African rand",
     "short_symbol": "",
     "symbol": "",
     "enum": "710",
     "usage": ["ZA"],
     "decimals": "2",
     "common_name": "South African rand",
     "nickname": ""},
    {"code": "ZMK",
     "name": "Zambian kwacha",
     "short_name": "Zambian kwacha",
     "short_symbol": "",
     "symbol": "",
     "enum": "894",
     "usage": ["ZM"],
     "decimals": "2",
     "common_name": "Zambian kwacha",
     "nickname": ""},
    {"code": "ZWL",
     "name": "Zimbabwe dollar",
     "short_name": "Zimbabwe dollar",
     "short_symbol": "",
     "symbol": "",
     "enum": "932",
     "usage": ["ZW"],
     "decimals": "2",
     "common_name": "Zimbabwe dollar",
     "nickname": ""}]

# Iterate over the raw currency data and populate currencies database:
Currency.put(*[Currency(currency["code"],
                        currency["enum"],
                        currency["name"],
                        currency["common_name"],
                        currency["short_name"],
                        currency["nickname"],
                        currency["symbol"],
                        currency["short_symbol"],
                        currency["decimals"],
                        [Country.get(code) for code in currency["usage"]])
               for currency in RawData])
